// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class CategoryTraitRule
{
    public int CategoryTraitTypeId { get; set; }

    public int CategoryId { get; set; }

    public int TraitTypeId { get; set; }

    public bool IsRequired { get; set; }

    public bool IsVisible { get; set; }

    public int DisplayOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}