// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ContainerType
{
    public int ContainerTypeId { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public decimal? DefaultCapacityLb { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}