// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GrainManagement.Models;

public partial class dbContext : DbContext
{
    public dbContext(DbContextOptions<dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AuditSetting> AuditSettings { get; set; }

    public virtual DbSet<AuditTrail> AuditTrails { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CategoryTraitRule> CategoryTraitRules { get; set; }

    public virtual DbSet<ChemicalLot> ChemicalLots { get; set; }

    public virtual DbSet<ChemicalTransaction> ChemicalTransactions { get; set; }

    public virtual DbSet<Container> Containers { get; set; }

    public virtual DbSet<ContainerLotLayer> ContainerLotLayers { get; set; }

    public virtual DbSet<ContainerType> ContainerTypes { get; set; }

    public virtual DbSet<CustomerPriceOverride> CustomerPriceOverrides { get; set; }

    public virtual DbSet<InventoryEvent> InventoryEvents { get; set; }

    public virtual DbSet<InventoryMovement> InventoryMovements { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemTrait> ItemTraits { get; set; }

    public virtual DbSet<LabResult> LabResults { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<LocationDistrict> LocationDistricts { get; set; }

    public virtual DbSet<Lot> Lots { get; set; }

    public virtual DbSet<LotComponent> LotComponents { get; set; }

    public virtual DbSet<LotLab> LotLabs { get; set; }

    public virtual DbSet<LotPriceOverride> LotPriceOverrides { get; set; }

    public virtual DbSet<LotTrait> LotTraits { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PriceAdjustment> PriceAdjustments { get; set; }

    public virtual DbSet<PriceList> PriceLists { get; set; }

    public virtual DbSet<PriceListLine> PriceListLines { get; set; }

    public virtual DbSet<PriceType> PriceTypes { get; set; }

    public virtual DbSet<Privilege> Privileges { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductAllowedTrait> ProductAllowedTraits { get; set; }

    public virtual DbSet<ProductGroup> ProductGroups { get; set; }

    public virtual DbSet<ProductLocationPrice> ProductLocationPrices { get; set; }

    public virtual DbSet<ProductLocationPricesLegacy> ProductLocationPricesLegacies { get; set; }

    public virtual DbSet<ProductRequiredTraitType> ProductRequiredTraitTypes { get; set; }

    public virtual DbSet<ProductTrait> ProductTraits { get; set; }

    public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }

    public virtual DbSet<PurchaseOrderLineItem> PurchaseOrderLineItems { get; set; }

    public virtual DbSet<ReceivedGrade> ReceivedGrades { get; set; }

    public virtual DbSet<ReceivedInventoryItem> ReceivedInventoryItems { get; set; }

    public virtual DbSet<ReceivedInventoryPurchaseOrderLineItem> ReceivedInventoryPurchaseOrderLineItems { get; set; }

    public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }

    public virtual DbSet<SalesInvoiceLineItem> SalesInvoiceLineItems { get; set; }

    public virtual DbSet<SalesInvoiceLineItemLot> SalesInvoiceLineItemLots { get; set; }

    public virtual DbSet<SalesOrder> SalesOrders { get; set; }

    public virtual DbSet<SalesOrderLineItem> SalesOrderLineItems { get; set; }

    public virtual DbSet<SeedTreatmentApplication> SeedTreatmentApplications { get; set; }

    public virtual DbSet<Server> Servers { get; set; }

    public virtual DbSet<SplitGroup> SplitGroups { get; set; }

    public virtual DbSet<SplitGroupPercent> SplitGroupPercents { get; set; }

    public virtual DbSet<SplitGroupsLookup> SplitGroupsLookups { get; set; }

    public virtual DbSet<SplitGroupsRead> SplitGroupsReads { get; set; }

    public virtual DbSet<StorageLocation> StorageLocations { get; set; }

    public virtual DbSet<Trait> Traits { get; set; }

    public virtual DbSet<TraitType> TraitTypes { get; set; }

    public virtual DbSet<Truck> Trucks { get; set; }

    public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }

    public virtual DbSet<UomType> UomTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserPrivilege> UserPrivileges { get; set; }

    public virtual DbSet<VwLotCondition> VwLotConditions { get; set; }

    public virtual DbSet<VwProductWarehouseVsMarket> VwProductWarehouseVsMarkets { get; set; }

    public virtual DbSet<WeightSheet> WeightSheets { get; set; }

    public virtual DbSet<WeightSheetLoad> WeightSheetLoads { get; set; }

    public virtual DbSet<WeightSheetLoadLotAllocation> WeightSheetLoadLotAllocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.ToTable("Accounts", "account");

            entity.HasIndex(e => e.As400AccountId, "IX_Accounts").IsUnique();

            entity.Property(e => e.Address1).HasMaxLength(255);
            entity.Property(e => e.Address2).HasMaxLength(255);
            entity.Property(e => e.City).HasMaxLength(255);
            entity.Property(e => e.Contact).HasMaxLength(255);
            entity.Property(e => e.Country).HasMaxLength(25);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_account_Accounts_CreatedAt");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.EntityName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.LookupName).HasMaxLength(200);
            entity.Property(e => e.MobilePhone).HasMaxLength(16);
            entity.Property(e => e.OwnerFirstName).HasMaxLength(200);
            entity.Property(e => e.OwnerLastName).HasMaxLength(200);
            entity.Property(e => e.Phone1).HasMaxLength(16);
            entity.Property(e => e.Phone2).HasMaxLength(16);
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.TaxId).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.Zip).HasMaxLength(20);
        });

        modelBuilder.Entity<AuditSetting>(entity =>
        {
            entity.HasKey(e => e.AuditSettingsId).HasName("PK_AuditSettingsId");

            entity.ToTable("AuditSettings", "system");

            entity.Property(e => e.Setting).HasMaxLength(255);
        });

        modelBuilder.Entity<AuditTrail>(entity =>
        {
            entity.HasKey(e => e.AuditId);

            entity.ToTable("AuditTrail", "system");

            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_system_AuditTrail_CreatedAt");
            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Categories", "product");

            entity.Property(e => e.CategoryCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Categories_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<CategoryTraitRule>(entity =>
        {
            entity.HasKey(e => e.CategoryTraitTypeId).HasName("PK_CategoryTraitTypes");

            entity.ToTable("CategoryTraitRules", "product");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryTraitRules_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<ChemicalLot>(entity =>
        {
            entity.ToTable("ChemicalLots", "chem");

            entity.HasIndex(e => new { e.ProductId, e.LocationId, e.ExpirationDate }, "IX_ChemicalLots_Product_Location_Exp");

            entity.HasIndex(e => e.RowGuid, "UX_ChemicalLots_RowGuid").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalLots_CreatedAt");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalLots_IsActive");
            entity.Property(e => e.QtyOnHand)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalLots_QtyOnHand")
                .HasColumnType("decimal(18, 6)");
            entity.Property(e => e.ReceivedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalLots_ReceivedAt");
            entity.Property(e => e.RowGuid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalLots_RowGuid");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.VendorLotNumber)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Location).WithMany(p => p.ChemicalLots)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChemicalLots_Location");

            entity.HasOne(d => d.Product).WithMany(p => p.ChemicalLots)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChemicalLots_Product");

            entity.HasOne(d => d.Uom).WithMany(p => p.ChemicalLots)
                .HasForeignKey(d => d.UomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChemicalLots_Uom");
        });

        modelBuilder.Entity<ChemicalTransaction>(entity =>
        {
            entity.HasKey(e => e.ChemicalTxnId);

            entity.ToTable("ChemicalTransactions", "chem");

            entity.HasIndex(e => new { e.ChemicalLotId, e.TxnAt }, "IX_ChemicalTx_Lot_TxnAt");

            entity.HasIndex(e => new { e.RefTable, e.RefId }, "IX_ChemicalTx_Ref");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalTx_CreatedAt");
            entity.Property(e => e.Note).HasMaxLength(200);
            entity.Property(e => e.Qty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.RefTable).HasMaxLength(50);
            entity.Property(e => e.TxnAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ChemicalTx_TxnAt");
            entity.Property(e => e.TxnType)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.ChemicalLot).WithMany(p => p.ChemicalTransactions)
                .HasForeignKey(d => d.ChemicalLotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChemicalTx_Lot");

            entity.HasOne(d => d.Uom).WithMany(p => p.ChemicalTransactions)
                .HasForeignKey(d => d.UomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChemicalTx_Uom");
        });

        modelBuilder.Entity<Container>(entity =>
        {
            entity.ToTable("Containers", "container");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CapacityLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_container_Containers_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<ContainerLotLayer>(entity =>
        {
            entity.ToTable("ContainerLotLayers", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_ContainerLotLayers_CreatedAt");
            entity.Property(e => e.Moisture).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.Protein).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.QtyLbIn).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.QtyLbRemaining).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<ContainerType>(entity =>
        {
            entity.ToTable("ContainerTypes", "container");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_container_ContainerTypes_CreatedAt");
            entity.Property(e => e.DefaultCapacityLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<CustomerPriceOverride>(entity =>
        {
            entity.ToTable("CustomerPriceOverrides", "sale");

            entity.HasIndex(e => new { e.AccountId, e.LocationId, e.PriceTypeId, e.CurrencyCode, e.EffectiveFrom }, "IX_CustomerPriceOverrides_Lookup");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CustomerPriceOverrides_CreatedAt");
            entity.Property(e => e.CurrencyCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EffectiveFrom).HasPrecision(0);
            entity.Property(e => e.EffectiveTo).HasPrecision(0);
            entity.Property(e => e.Priority).HasAnnotation("Relational:DefaultConstraintName", "DF_CustomerPriceOverrides_Priority");
            entity.Property(e => e.Reason).HasMaxLength(200);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Account).WithMany(p => p.CustomerPriceOverrides)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerPriceOverrides_Accounts");

            entity.HasOne(d => d.Item).WithMany(p => p.CustomerPriceOverrides)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_CustomerPriceOverrides_Items");

            entity.HasOne(d => d.Location).WithMany(p => p.CustomerPriceOverrides)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_CustomerPriceOverrides_Locations");

            entity.HasOne(d => d.PriceType).WithMany(p => p.CustomerPriceOverrides)
                .HasForeignKey(d => d.PriceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerPriceOverrides_PriceTypes");

            entity.HasOne(d => d.Product).WithMany(p => p.CustomerPriceOverrides)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_CustomerPriceOverrides_Products");
        });

        modelBuilder.Entity<InventoryEvent>(entity =>
        {
            entity.ToTable("InventoryEvents", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_InventoryEvents_CreatedAt");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.ReferenceUid).HasColumnName("ReferenceUID");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<InventoryMovement>(entity =>
        {
            entity.ToTable("InventoryMovements", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_InventoryMovements_CreatedAt");
            entity.Property(e => e.Moisture).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.Protein).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.ToTable("Items", "product");

            entity.HasIndex(e => e.Description, "IX_Items_1");

            entity.Property(e => e.ItemId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_product_Items_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Items_IsActive");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<ItemTrait>(entity =>
        {
            entity.HasKey(e => new { e.ItemId, e.TraitId });

            entity.ToTable("ItemTraits", "product");

            entity.HasIndex(e => new { e.ItemId, e.TraitTypeId }, "UX_ItemTraits_Exclusive")
                .IsUnique()
                .HasFilter("([IsExclusiveApplied]=(1))");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ItemTraits_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Item).WithMany(p => p.ItemTraits)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItemTraits_Item");

            entity.HasOne(d => d.Trait).WithMany(p => p.ItemTraitTraits)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItemTraits_Trait");

            entity.HasOne(d => d.TraitNavigation).WithMany(p => p.ItemTraitTraitNavigations)
                .HasPrincipalKey(p => new { p.TraitId, p.TraitTypeId })
                .HasForeignKey(d => new { d.TraitId, d.TraitTypeId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItemTraits_Trait_TraitType");
        });

        modelBuilder.Entity<LabResult>(entity =>
        {
            entity.ToTable("LabResults", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_LabResults_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Test)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.ToTable("Locations", "system");

            entity.Property(e => e.LocationId).ValueGeneratedNever();
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.District).WithMany(p => p.Locations)
                .HasForeignKey(d => d.DistrictId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Locations_LocationDistricts");
        });

        modelBuilder.Entity<LocationDistrict>(entity =>
        {
            entity.HasKey(e => e.DistrictId).HasName("PK_Districts");

            entity.ToTable("LocationDistricts", "system");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Lot>(entity =>
        {
            entity.ToTable("Lots", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_Lots_CreatedAt");
            entity.Property(e => e.LotDescription)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<LotComponent>(entity =>
        {
            entity.HasKey(e => new { e.ParentLotId, e.ChildLotId });

            entity.ToTable("LotComponents", "Inventory");

            entity.Property(e => e.ChildQtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_LotComponents_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<LotLab>(entity =>
        {
            entity.ToTable("LotLabs", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Inventory_LotLabs_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<LotPriceOverride>(entity =>
        {
            entity.ToTable("LotPriceOverrides", "Inventory");

            entity.HasIndex(e => new { e.LotId, e.PriceTypeId, e.CurrencyCode, e.EffectiveFrom }, "IX_LotPriceOverrides_Lookup");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LotPriceOverrides_CreatedAt");
            entity.Property(e => e.CurrencyCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EffectiveFrom).HasPrecision(0);
            entity.Property(e => e.EffectiveTo).HasPrecision(0);
            entity.Property(e => e.PremiumDiscount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Reason).HasMaxLength(200);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Account).WithMany(p => p.LotPriceOverrides)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_LotPriceOverrides_Accounts");

            entity.HasOne(d => d.Lot).WithMany(p => p.LotPriceOverrides)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotPriceOverrides_Lots");

            entity.HasOne(d => d.PriceType).WithMany(p => p.LotPriceOverrides)
                .HasForeignKey(d => d.PriceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotPriceOverrides_PriceTypes");
        });

        modelBuilder.Entity<LotTrait>(entity =>
        {
            entity.ToTable("LotTraits", "Inventory");

            entity.HasIndex(e => new { e.TraitId, e.LotId }, "IX_LotTraits_Trait");

            entity.HasIndex(e => new { e.LotId, e.TraitTypeId }, "UX_LotTraits_Exclusive")
                .IsUnique()
                .HasFilter("([IsExclusive]=(1))");

            entity.HasIndex(e => new { e.LotId, e.TraitTypeId }, "UX_LotTraits_ExclusiveType")
                .IsUnique()
                .HasFilter("([IsExclusive]=(1))");

            entity.HasIndex(e => new { e.LotId, e.TraitId }, "UX_LotTraits_Lot_Trait").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LotTraits_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Lot).WithMany(p => p.LotTraits)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotTraits_Lot");

            entity.HasOne(d => d.Trait).WithMany(p => p.LotTraitTraits)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotTraits_Trait");

            entity.HasOne(d => d.TraitType).WithMany(p => p.LotTraits)
                .HasForeignKey(d => d.TraitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotTraits_TraitType");

            entity.HasOne(d => d.TraitNavigation).WithMany(p => p.LotTraitTraitNavigations)
                .HasPrincipalKey(p => new { p.TraitId, p.TraitTypeId })
                .HasForeignKey(d => new { d.TraitId, d.TraitTypeId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotTraits_Trait_TraitType");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.ToTable("Payments", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_Payments_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Reference).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Account).WithMany(p => p.Payments)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_Payments_Account");

            entity.HasOne(d => d.SalesInvoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SalesInvoiceId)
                .HasConstraintName("FK_Payments_Invoice");
        });

        modelBuilder.Entity<PriceAdjustment>(entity =>
        {
            entity.ToTable("PriceAdjustments", "product");

            entity.HasIndex(e => new { e.PriceListId, e.TraitTypeId, e.TraitId }, "IX_PriceAdjustments_PriceList_Trait");

            entity.Property(e => e.AdjustmentType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.AdjustmentValue).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PriceAdjustments_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.PriceList).WithMany(p => p.PriceAdjustments)
                .HasForeignKey(d => d.PriceListId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceAdjustments_PriceLists");

            entity.HasOne(d => d.Trait).WithMany(p => p.PriceAdjustments)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceAdjustments_Traits");

            entity.HasOne(d => d.TraitType).WithMany(p => p.PriceAdjustments)
                .HasForeignKey(d => d.TraitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceAdjustments_TraitTypes");
        });

        modelBuilder.Entity<PriceList>(entity =>
        {
            entity.ToTable("PriceLists", "product");

            entity.HasIndex(e => new { e.LocationId, e.PriceTypeId, e.CurrencyCode, e.EffectiveFrom }, "IX_PriceLists_Location_Type_Effective");

            entity.HasIndex(e => new { e.LocationId, e.PriceTypeId, e.CurrencyCode, e.EffectiveFrom, e.EffectiveTo }, "UX_PriceLists_Key").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PriceLists_CreatedAt");
            entity.Property(e => e.CurrencyCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EffectiveFrom).HasPrecision(0);
            entity.Property(e => e.EffectiveTo).HasPrecision(0);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Priority).HasAnnotation("Relational:DefaultConstraintName", "DF_PriceLists_Priority");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Location).WithMany(p => p.PriceLists)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceLists_Locations");

            entity.HasOne(d => d.PriceType).WithMany(p => p.PriceLists)
                .HasForeignKey(d => d.PriceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceLists_PriceTypes");
        });

        modelBuilder.Entity<PriceListLine>(entity =>
        {
            entity.ToTable("PriceListLines", "product");

            entity.HasIndex(e => new { e.PriceListId, e.ItemId }, "IX_PriceListLines_PriceList_Item").HasFilter("([ItemId] IS NOT NULL)");

            entity.HasIndex(e => new { e.PriceListId, e.ProductId }, "IX_PriceListLines_PriceList_Product").HasFilter("([ProductId] IS NOT NULL)");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PriceListLines_CreatedAt");
            entity.Property(e => e.MaxQty).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.MinQty).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Item).WithMany(p => p.PriceListLines)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_PriceListLines_Items");

            entity.HasOne(d => d.PriceList).WithMany(p => p.PriceListLines)
                .HasForeignKey(d => d.PriceListId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PriceListLines_PriceLists");

            entity.HasOne(d => d.Product).WithMany(p => p.PriceListLines)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_PriceListLines_Products");

            entity.HasOne(d => d.Uom).WithMany(p => p.PriceListLines)
                .HasForeignKey(d => d.UomId)
                .HasConstraintName("FK_PriceListLines_Uom");
        });

        modelBuilder.Entity<PriceType>(entity =>
        {
            entity.ToTable("PriceTypes", "product");

            entity.HasIndex(e => e.Code, "UX_PriceTypes_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PriceTypes_CreatedAt");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PriceTypes_IsActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<Privilege>(entity =>
        {
            entity.ToTable("Privileges", "users");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Products", "product");

            entity.HasIndex(e => e.ProductCode, "IX_Products").IsUnique();

            entity.HasIndex(e => e.Description, "IX_Products_1");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_product_Products_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Category");

            entity.HasOne(d => d.ProductGroup).WithMany(p => p.Products)
                .HasForeignKey(d => d.ProductGroupId)
                .HasConstraintName("FK_Products_ProductGroup");
        });

        modelBuilder.Entity<ProductAllowedTrait>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.TraitId });

            entity.ToTable("ProductAllowedTraits", "product");

            entity.HasIndex(e => e.TraitId, "IX_ProductAllowedTraits_TraitId");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_product_ProductAllowedTraits_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductAllowedTraits)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAllowedTraits_Product");

            entity.HasOne(d => d.Trait).WithMany(p => p.ProductAllowedTraits)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAllowedTraits_Trait");
        });

        modelBuilder.Entity<ProductGroup>(entity =>
        {
            entity.ToTable("ProductGroups", "product");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroups_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.GroupCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Category).WithMany(p => p.ProductGroups)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductGroups_Category");
        });

        modelBuilder.Entity<ProductLocationPrice>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ProductLocationPrices", "product");

            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EffectiveFrom).HasPrecision(0);
            entity.Property(e => e.EffectiveTo).HasPrecision(0);
            entity.Property(e => e.RetailPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.WholesalePrice).HasColumnType("decimal(18, 4)");
        });

        modelBuilder.Entity<ProductLocationPricesLegacy>(entity =>
        {
            entity.HasKey(e => e.ProductLocationPriceId).HasName("PK_ProductLocationPrices");

            entity.ToTable("ProductLocationPrices_Legacy", "product");

            entity.HasIndex(e => new { e.LocationId, e.ProductId }, "IX_ProductLocationPrices_Location");

            entity.HasIndex(e => new { e.ProductId, e.LocationId }, "UX_ProductLocationPrices_Current")
                .IsUnique()
                .HasFilter("([EffectiveTo] IS NULL)");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductLocationPrices_CreatedAt");
            entity.Property(e => e.CurrencyCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("USD")
                .IsFixedLength()
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductLocationPrices_CurrencyCode");
            entity.Property(e => e.EffectiveFrom)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductLocationPrices_EffectiveFrom");
            entity.Property(e => e.EffectiveTo).HasPrecision(0);
            entity.Property(e => e.RetailPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductLocationPrices_UpdatedAt");
            entity.Property(e => e.WholesalePrice).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.Location).WithMany(p => p.ProductLocationPricesLegacies)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLocationPrices_Location");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductLocationPricesLegacies)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLocationPrices_Product");
        });

        modelBuilder.Entity<ProductRequiredTraitType>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.TraitTypeId });

            entity.ToTable("ProductRequiredTraitTypes", "product");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_product_ProductRequiredTraitTypes_CreatedAt");
            entity.Property(e => e.IsRequired)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductRequiredTraitTypes_IsRequired");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductRequiredTraitTypes)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductRequiredTraitTypes_Product");

            entity.HasOne(d => d.TraitType).WithMany(p => p.ProductRequiredTraitTypes)
                .HasForeignKey(d => d.TraitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductRequiredTraitTypes_TraitType");
        });

        modelBuilder.Entity<ProductTrait>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.TraitId });

            entity.ToTable("ProductTraits", "product");

            entity.HasIndex(e => new { e.ProductId, e.TraitTypeId }, "UX_ProductTraits_ExclusiveType")
                .IsUnique()
                .HasFilter("([IsExclusiveApplied]=(1))");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductTraits_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductTraits)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductTraits_Product");

            entity.HasOne(d => d.Trait).WithMany(p => p.ProductTraitTraits)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductTraits_Trait");

            entity.HasOne(d => d.TraitNavigation).WithMany(p => p.ProductTraitTraitNavigations)
                .HasPrincipalKey(p => new { p.TraitId, p.TraitTypeId })
                .HasForeignKey(d => new { d.TraitId, d.TraitTypeId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductTraits_Trait_TraitType");
        });

        modelBuilder.Entity<PurchaseOrder>(entity =>
        {
            entity.ToTable("PurchaseOrders", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_PurchaseOrders_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Location).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_Location");

            entity.HasOne(d => d.VendorAccount).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.VendorAccountId)
                .HasConstraintName("FK_PurchaseOrders_Vendor");
        });

        modelBuilder.Entity<PurchaseOrderLineItem>(entity =>
        {
            entity.ToTable("PurchaseOrderLineItems", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ContractPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_PurchaseOrderLineItems_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QtyLbOrdered).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.QtyLbUnpriced).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.PurchaseOrder).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.PurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POLI_PO");
        });

        modelBuilder.Entity<ReceivedGrade>(entity =>
        {
            entity.ToTable("ReceivedGrades", "seed");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_seed_ReceivedGrades_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Test)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.ReceivedInventoryItem).WithMany(p => p.ReceivedGrades)
                .HasForeignKey(d => d.ReceivedInventoryItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivedGrades_RII");
        });

        modelBuilder.Entity<ReceivedInventoryItem>(entity =>
        {
            entity.ToTable("ReceivedInventoryItems", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_ReceivedInventoryItems_CreatedAt");
            entity.Property(e => e.Moisture).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.NetLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Protein).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Location).WithMany(p => p.ReceivedInventoryItems)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RII_Location");

            entity.HasOne(d => d.Lot).WithMany(p => p.ReceivedInventoryItems)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RII_Lot");

            entity.HasOne(d => d.PurchaseOrderLineItem).WithMany(p => p.ReceivedInventoryItems)
                .HasForeignKey(d => d.PurchaseOrderLineItemId)
                .HasConstraintName("FK_RII_POLI");
        });

        modelBuilder.Entity<ReceivedInventoryPurchaseOrderLineItem>(entity =>
        {
            entity.ToTable("ReceivedInventoryPurchaseOrderLineItems", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_ReceivedInventoryPurchaseOrderLineItems_CreatedAt");
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.PurchaseOrderLineItem).WithMany(p => p.ReceivedInventoryPurchaseOrderLineItems)
                .HasForeignKey(d => d.PurchaseOrderLineItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RIPOLI_POLI");

            entity.HasOne(d => d.ReceivedInventoryItem).WithMany(p => p.ReceivedInventoryPurchaseOrderLineItems)
                .HasForeignKey(d => d.ReceivedInventoryItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RIPOLI_RII");
        });

        modelBuilder.Entity<SalesInvoice>(entity =>
        {
            entity.ToTable("SalesInvoices", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_SalesInvoices_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Location).WithMany(p => p.SalesInvoices)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesInvoices_Location");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesInvoices)
                .HasForeignKey(d => d.SalesOrderId)
                .HasConstraintName("FK_SalesInvoices_Order");
        });

        modelBuilder.Entity<SalesInvoiceLineItem>(entity =>
        {
            entity.ToTable("SalesInvoiceLineItems", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_SalesInvoiceLineItems_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.SalesOrderLineItem).WithMany(p => p.SalesInvoiceLineItems)
                .HasForeignKey(d => d.SalesOrderLineItemId)
                .HasConstraintName("FK_SILI_OrderLine");
        });

        modelBuilder.Entity<SalesInvoiceLineItemLot>(entity =>
        {
            entity.ToTable("SalesInvoiceLineItemLots", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_SalesInvoiceLineItemLots_CreatedAt");
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Lot).WithMany(p => p.SalesInvoiceLineItemLots)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SILIL_Lot");

            entity.HasOne(d => d.SalesInvoiceLineItem).WithMany(p => p.SalesInvoiceLineItemLots)
                .HasForeignKey(d => d.SalesInvoiceLineItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SILIL_Line");
        });

        modelBuilder.Entity<SalesOrder>(entity =>
        {
            entity.ToTable("SalesOrders", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_SalesOrders_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.CustomerAccount).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.CustomerAccountId)
                .HasConstraintName("FK_SalesOrders_Customer");

            entity.HasOne(d => d.Location).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrders_Location");
        });

        modelBuilder.Entity<SalesOrderLineItem>(entity =>
        {
            entity.ToTable("SalesOrderLineItems", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BlendPercent).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_sale_SalesOrderLineItems_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.QuotedUnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderLineItems)
                .HasForeignKey(d => d.SalesOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOLI_Order");
        });

        modelBuilder.Entity<SeedTreatmentApplication>(entity =>
        {
            entity.HasKey(e => e.ApplicationId);

            entity.ToTable("SeedTreatmentApplications", "chem");

            entity.HasIndex(e => new { e.ChemicalLotId, e.AppliedAt }, "IX_SeedTreatApps_ChemLot_AppliedAt");

            entity.HasIndex(e => new { e.SeedLotId, e.AppliedAt }, "IX_SeedTreatApps_SeedLot_AppliedAt");

            entity.HasIndex(e => e.RowGuid, "UX_SeedTreatApps_RowGuid").IsUnique();

            entity.Property(e => e.AppliedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedTreatApps_AppliedAt");
            entity.Property(e => e.ChemicalUsedQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Comments).HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedTreatApps_CreatedAt");
            entity.Property(e => e.RowGuid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedTreatApps_RowGuid");
            entity.Property(e => e.SeedTreatedQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.ChemicalLot).WithMany(p => p.SeedTreatmentApplications)
                .HasForeignKey(d => d.ChemicalLotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeedTreatApps_ChemLot");

            entity.HasOne(d => d.ChemicalUsedUom).WithMany(p => p.SeedTreatmentApplicationChemicalUsedUoms)
                .HasForeignKey(d => d.ChemicalUsedUomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeedTreatApps_ChemUsedUom");

            entity.HasOne(d => d.OperatorUser).WithMany(p => p.SeedTreatmentApplications)
                .HasForeignKey(d => d.OperatorUserId)
                .HasConstraintName("FK_SeedTreatApps_Operator");

            entity.HasOne(d => d.SeedLot).WithMany(p => p.SeedTreatmentApplications)
                .HasForeignKey(d => d.SeedLotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeedTreatApps_SeedLot");

            entity.HasOne(d => d.SeedTreatedUom).WithMany(p => p.SeedTreatmentApplicationSeedTreatedUoms)
                .HasForeignKey(d => d.SeedTreatedUomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeedTreatApps_SeedUom");
        });

        modelBuilder.Entity<Server>(entity =>
        {
            entity.ToTable("Servers", "system");

            entity.Property(e => e.ServerId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_system_Servers_CreatedAt");
            entity.Property(e => e.ServerName)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<SplitGroup>(entity =>
        {
            entity.ToTable("SplitGroups", "account");

            entity.Property(e => e.SplitGroupId).ValueGeneratedNever();
            entity.Property(e => e.SplitGroupDescription)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UseForReceive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SplitGroups_UseForReceive");
            entity.Property(e => e.UseForSales)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SplitGroups_UseForSales");

            entity.HasOne(d => d.PrimaryAccount).WithMany(p => p.SplitGroups)
                .HasForeignKey(d => d.PrimaryAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SplitGroups_Accounts");
        });

        modelBuilder.Entity<SplitGroupPercent>(entity =>
        {
            entity.ToTable("SplitGroupPercents", "account");

            entity.Property(e => e.SplitPercent).HasColumnType("decimal(10, 7)");

            entity.HasOne(d => d.Account).WithMany(p => p.SplitGroupPercents)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SplitGroupPercents_Accounts");

            entity.HasOne(d => d.SplitGroup).WithMany(p => p.SplitGroupPercents)
                .HasForeignKey(d => d.SplitGroupId)
                .HasConstraintName("FK_SplitGroupPercents_SplitGroups");
        });

        modelBuilder.Entity<SplitGroupsLookup>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SplitGroupsLookup", "account");

            entity.Property(e => e.Account).HasMaxLength(200);
            entity.Property(e => e.PrimaryAccount).HasMaxLength(200);
            entity.Property(e => e.SplitGroupDescription)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.SplitPercent).HasColumnType("decimal(10, 7)");
        });

        modelBuilder.Entity<SplitGroupsRead>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SplitGroupsRead", "account");

            entity.Property(e => e.Account).HasMaxLength(200);
            entity.Property(e => e.PrimaryAccount).HasMaxLength(200);
            entity.Property(e => e.SplitGroupDescription)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.SplitPercent).HasColumnType("decimal(10, 7)");
        });

        modelBuilder.Entity<StorageLocation>(entity =>
        {
            entity.ToTable("StorageLocations", "container");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_container_StorageLocations_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<Trait>(entity =>
        {
            entity.ToTable("Traits", "product");

            entity.HasIndex(e => new { e.TraitId, e.TraitTypeId }, "UQ_Traits_TraitId_TraitTypeId").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_product_Traits_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TraitCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.TraitType).WithMany(p => p.Traits)
                .HasForeignKey(d => d.TraitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Traits_TraitTypes");
        });

        modelBuilder.Entity<TraitType>(entity =>
        {
            entity.ToTable("TraitTypes", "product");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TraitTypes_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TypeCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<Truck>(entity =>
        {
            entity.ToTable("Trucks", "account");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_account_Trucks_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.TareLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<UnitOfMeasure>(entity =>
        {
            entity.HasKey(e => e.UomId);

            entity.ToTable("UnitOfMeasures", "system");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_system_UnitOfMeasures_CreatedAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ToBaseFactor).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.UomType).WithMany(p => p.UnitOfMeasures)
                .HasForeignKey(d => d.UomTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Uom_UomTypes");
        });

        modelBuilder.Entity<UomType>(entity =>
        {
            entity.ToTable("UomTypes", "system");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_system_UomTypes_CreatedAt");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("Users", "users");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_users_Users_CreatedAt");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<UserPrivilege>(entity =>
        {
            entity.ToTable("UserPrivileges", "users");

            entity.HasOne(d => d.Privilege).WithMany(p => p.UserPrivileges)
                .HasForeignKey(d => d.PrivilegeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivileges_Privileges");

            entity.HasOne(d => d.User).WithMany(p => p.UserPrivileges)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivileges_Users");
        });

        modelBuilder.Entity<VwLotCondition>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_LotCondition", "Inventory");

            entity.Property(e => e.ConditionCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.ConditionDescription)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<VwProductWarehouseVsMarket>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ProductWarehouseVsMarket", "product");

            entity.Property(e => e.CategoryCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CategoryDescription)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProductDescription)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.WarehouseGroupCode).HasMaxLength(30);
            entity.Property(e => e.WarehouseGroupDescription).HasMaxLength(100);
        });

        modelBuilder.Entity<WeightSheet>(entity =>
        {
            entity.HasKey(e => e.WeightSheetUid);

            entity.ToTable("WeightSheets", "purchase");

            entity.Property(e => e.WeightSheetUid)
                .ValueGeneratedNever()
                .HasColumnName("WeightSheetUID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_WeightSheets_CreatedAt");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.SheetType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.VoidReason).HasMaxLength(200);

            entity.HasOne(d => d.CarrierAccount).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.CarrierAccountId)
                .HasConstraintName("FK_WeightSheets_Carrier");

            entity.HasOne(d => d.Location).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WeightSheets_Location");

            entity.HasOne(d => d.Lot).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.LotId)
                .HasConstraintName("FK_WeightSheets_Lot");

            entity.HasOne(d => d.Truck).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.TruckId)
                .HasConstraintName("FK_WeightSheets_Truck");
        });

        modelBuilder.Entity<WeightSheetLoad>(entity =>
        {
            entity.ToTable("WeightSheetLoads", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_WeightSheetLoads_CreatedAt");
            entity.Property(e => e.GrossLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Moisture).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.NetLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Protein).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.TareLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.WeightSheetUid).HasColumnName("WeightSheetUID");

            entity.HasOne(d => d.DestinationContainer).WithMany(p => p.WeightSheetLoadDestinationContainers)
                .HasForeignKey(d => d.DestinationContainerId)
                .HasConstraintName("FK_WSL_DestinationContainer");

            entity.HasOne(d => d.SourceContainer).WithMany(p => p.WeightSheetLoadSourceContainers)
                .HasForeignKey(d => d.SourceContainerId)
                .HasConstraintName("FK_WSL_SourceContainer");

            entity.HasOne(d => d.WeightSheetU).WithMany(p => p.WeightSheetLoads)
                .HasForeignKey(d => d.WeightSheetUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WSL_WeightSheet");
        });

        modelBuilder.Entity<WeightSheetLoadLotAllocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_WeightSheetLoadLotAlloc");

            entity.ToTable("WeightSheetLoadLotAllocations", "purchase");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_purchase_WeightSheetLoadLotAllocations_CreatedAt");
            entity.Property(e => e.QtyLb).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedAt).HasPrecision(0);

            entity.HasOne(d => d.Lot).WithMany(p => p.WeightSheetLoadLotAllocations)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WSLotAlloc_Lot");

            entity.HasOne(d => d.WeightSheetLoad).WithMany(p => p.WeightSheetLoadLotAllocations)
                .HasForeignKey(d => d.WeightSheetLoadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WSLotAlloc_Load");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}