// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ItemTrait
{
    public long ItemId { get; set; }

    public int TraitId { get; set; }

    public int TraitTypeId { get; set; }

    public bool IsExclusiveApplied { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Item Item { get; set; }

    public virtual Trait Trait { get; set; }

    public virtual Trait TraitNavigation { get; set; }
}