// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class LabResult
{
    public long Id { get; set; }

    public Guid RowGuid { get; set; }

    public long LotLabId { get; set; }

    public string Test { get; set; }

    public string Result { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}