// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class LotPriceOverride
{
    public long LotPriceOverrideId { get; set; }

    public long LotId { get; set; }

    public int PriceTypeId { get; set; }

    public long? AccountId { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? PremiumDiscount { get; set; }

    public string CurrencyCode { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Lot Lot { get; set; }

    public virtual PriceType PriceType { get; set; }
}