// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class PriceAdjustment
{
    public int PriceAdjustmentId { get; set; }

    public int PriceListId { get; set; }

    public int TraitTypeId { get; set; }

    public int TraitId { get; set; }

    public string AdjustmentType { get; set; }

    public decimal AdjustmentValue { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual PriceList PriceList { get; set; }

    public virtual Trait Trait { get; set; }

    public virtual TraitType TraitType { get; set; }
}