// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class Privilege
{
    public int PrivilegeId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<UserPrivilege> UserPrivileges { get; set; } = new List<UserPrivilege>();
}