// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class PurchaseOrderLineItemDetail
{
    public long PurchaseOrderLineItemId { get; set; }

    public long? ItemId { get; set; }

    public int? ProductId { get; set; }

    public decimal QtyLbOrdered { get; set; }

    public decimal? ContractPrice { get; set; }

    public decimal? QtyLbUnpriced { get; set; }

    public string Notes { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Item Item { get; set; }

    public virtual Product Product { get; set; }

    public virtual PurchaseOrderLineItem PurchaseOrderLineItem { get; set; }
}