// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class QuantitySourceType
{
    public int QuantitySourceTypeId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<QuantityMethodSource> QuantityMethodSources { get; set; } = new List<QuantityMethodSource>();

    public virtual ICollection<TransactionQuantitySource> TransactionQuantitySources { get; set; } = new List<TransactionQuantitySource>();
}
