// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ReceivedInventoryPurchaseOrderLineItem
{
    public long Id { get; set; }

    public Guid RowGuid { get; set; }

    public long ReceivedInventoryItemId { get; set; }

    public long PurchaseOrderLineItemId { get; set; }

    public decimal QtyLb { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ReceivedInventoryItem ReceivedInventoryItem { get; set; }
}