// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ReceivedInventoryItem
{
    public long Id { get; set; }

    public Guid RowGuid { get; set; }

    public int LocationId { get; set; }

    public DateTime ReceivedAt { get; set; }

    public long? ItemId { get; set; }

    public int? ProductId { get; set; }

    public long LotId { get; set; }

    public long ContainerId { get; set; }

    public decimal NetLb { get; set; }

    public decimal? Protein { get; set; }

    public decimal? Moisture { get; set; }

    public long? PurchaseOrderLineItemId { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Location Location { get; set; }

    public virtual Lot Lot { get; set; }

    public virtual PurchaseOrderLineItem PurchaseOrderLineItem { get; set; }

    public virtual ICollection<ReceivedGrade> ReceivedGrades { get; set; } = new List<ReceivedGrade>();

    public virtual ICollection<ReceivedInventoryPurchaseOrderLineItem> ReceivedInventoryPurchaseOrderLineItems { get; set; } = new List<ReceivedInventoryPurchaseOrderLineItem>();
}