// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class SalesInvoiceLineItem
{
    public long Id { get; set; }

    public Guid RowGuid { get; set; }

    public long SalesInvoiceId { get; set; }

    public long? SalesOrderLineItemId { get; set; }

    public long? ItemId { get; set; }

    public int? ProductId { get; set; }

    public decimal QtyLb { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<SalesInvoiceLineItemLot> SalesInvoiceLineItemLots { get; set; } = new List<SalesInvoiceLineItemLot>();

    public virtual SalesOrderLineItem SalesOrderLineItem { get; set; }
}