// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class Server
{
    public int ServerId { get; set; }

    public string ServerName { get; set; }

    public string FriendlyName { get; set; }

    public bool IsActive { get; set; }

    public string Url { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}