// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class SplitGroup
{
    public int SplitGroupId { get; set; }

    public long PrimaryAccountId { get; set; }

    public string SplitGroupDescription { get; set; }

    public bool IsActive { get; set; }

    public bool UseForSales { get; set; }

    public bool UseForReceive { get; set; }

    public virtual ICollection<InventoryTransactionDetail> InventoryTransactionDetails { get; set; } = new List<InventoryTransactionDetail>();

    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    public virtual Account PrimaryAccount { get; set; }

    public virtual ICollection<SplitGroupPercent> SplitGroupPercents { get; set; } = new List<SplitGroupPercent>();
}