// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class VwProductWarehouseVsMarket
{
    public int CategoryId { get; set; }

    public string CategoryCode { get; set; }

    public string CategoryDescription { get; set; }

    public int? ProductGroupId { get; set; }

    public string WarehouseGroupCode { get; set; }

    public string WarehouseGroupDescription { get; set; }

    public bool? WarehouseGroupIsActive { get; set; }

    public int ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductDescription { get; set; }

    public bool ProductIsActive { get; set; }

    public bool ProductIsHidden { get; set; }
}