// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class WeightSheetLoadLotAllocation
{
    public long Id { get; set; }

    public Guid RowGuid { get; set; }

    public long WeightSheetLoadId { get; set; }

    public long LotId { get; set; }

    public decimal QtyLb { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Lot Lot { get; set; }

    public virtual WeightSheetLoad WeightSheetLoad { get; set; }
}