// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Agvantage_Transfer.AtLogModels;

public partial class AgvantageTransferLog
{
    public Guid Uid { get; set; }

    public DateTime TaskTime { get; set; }

    public bool Error { get; set; }

    public string Event { get; set; }

    public string Message { get; set; }
}