// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace EFOptions.Dto
{

    public partial class TransferFilterDto

    {
        public Guid Uid { get; set; }

        public int SourceLocationId { get; set; }
        public int DestinationId { get; set; }

        public string SourceDescription { get; set; }
        public string DestinationDescription { get; set; }

        
    }
}