// <auto-generated />
using System;
using BasicWeigh.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicWeigh.Web.Migrations
{
    [DbContext(typeof(ScaleDbContext))]
    [Migration("20260321152159_AddUserLoginSystem")]
    partial class AddUserLoginSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("BasicWeigh.Web.Models.AppSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DemoMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<string>("IconContentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("KioskCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("KioskCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KioskDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PromptKioskCarrier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskCommodity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskDestinationOnInbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskDestinationOnOutbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLogin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSetup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoMode = false,
                            Header1 = "Basic Weigh",
                            Header2 = "",
                            Header3 = "",
                            Header4 = "",
                            KioskCode = "12345",
                            KioskCount = 0,
                            KioskDarkMode = true,
                            PromptKioskCarrier = true,
                            PromptKioskCommodity = true,
                            PromptKioskCustomer = true,
                            PromptKioskDestinationOnInbound = false,
                            PromptKioskDestinationOnOutbound = true,
                            PromptKioskLocation = true,
                            PromptKioskTruckId = true,
                            Theme = "default",
                            TicketNumber = 1,
                            TicketsPerPage = 1,
                            UseLogin = false
                        });
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CarrierName")
                        .IsUnique();

                    b.ToTable("Carriers", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CommodityName")
                        .IsUnique();

                    b.ToTable("Commodities", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CustomerName")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("DestinationName")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Transaction", b =>
                {
                    b.Property<string>("Ticket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualInbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TruckId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Void")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ticket");

                    b.HasIndex("Carrier");

                    b.HasIndex("Customer");

                    b.HasIndex("DateIn");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TruckId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("TruckId", "CarrierName")
                        .IsUnique();

                    b.ToTable("Trucks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
