// <auto-generated />
using System;
using BasicWeigh.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicWeigh.Web.Migrations
{
    [DbContext(typeof(ScaleDbContext))]
    [Migration("20260319193821_AddManualInboundOutbound")]
    partial class AddManualInboundOutbound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("BasicWeigh.Web.Models.AppSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DemoMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<string>("IconContentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KioskCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsPerPage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSetup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoMode = false,
                            Header1 = "Basic Weigh",
                            Header2 = "",
                            Header3 = "",
                            Header4 = "",
                            KioskCount = 0,
                            TicketNumber = 1,
                            TicketsPerPage = 1
                        });
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Carrier", b =>
                {
                    b.Property<string>("CarrierName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarrierName");

                    b.ToTable("Carriers", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Commodity", b =>
                {
                    b.Property<string>("CommodityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommodityName");

                    b.ToTable("Commodities", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Customer", b =>
                {
                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerName");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Destination", b =>
                {
                    b.Property<string>("DestinationName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("DestinationName");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Location", b =>
                {
                    b.Property<string>("LocationName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationName");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Transaction", b =>
                {
                    b.Property<string>("Ticket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualInbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TruckId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Void")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ticket");

                    b.HasIndex("Carrier");

                    b.HasIndex("Customer");

                    b.HasIndex("DateIn");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("BasicWeigh.Web.Models.Truck", b =>
                {
                    b.Property<string>("TruckId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lot")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TruckId", "CarrierName");

                    b.ToTable("Trucks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
