// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class AccountGroup
{
    public Guid Uid { get; set; }

    public string Description { get; set; }

    public bool Active { get; set; }

    public string Notes { get; set; }

    public Guid PrimaryAccountUid { get; set; }

    public bool UseForSales { get; set; }

    public bool UseForReceive { get; set; }

    public virtual ICollection<AssociatedGroupAccount> AssociatedGroupAccounts { get; set; } = new List<AssociatedGroupAccount>();

    public virtual Account PrimaryAccountU { get; set; }
}