// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ContainerStyle
{
    public int Id { get; set; }

    public string Style { get; set; }

    public bool FixedLocation { get; set; }

    public bool AutoAssign { get; set; }

    public bool Grouped { get; set; }

    public bool Hidden { get; set; }

    public string Notes { get; set; }
}