// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class Container
{
    public long Id { get; set; }

    public string Description { get; set; }

    public Guid ContainerTypeUid { get; set; }

    public Guid StorageLocationUid { get; set; }

    public long Capacity { get; set; }

    public bool Active { get; set; }

    public bool Destroyed { get; set; }

    public float Tare { get; set; }

    public bool NotForSeed { get; set; }

    public bool CleanerBin { get; set; }

    public string Notes { get; set; }

    public string CustomerId { get; set; }

    public bool Virtual { get; set; }

    public string Coordinates { get; set; }
}