// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GrainManagement.Models;

public partial class dbContext : DbContext
{
    public dbContext(DbContextOptions<dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountCustomPricing> AccountCustomPricings { get; set; }

    public virtual DbSet<AlertEmail> AlertEmails { get; set; }

    public virtual DbSet<AssignedProductClass> AssignedProductClasses { get; set; }

    public virtual DbSet<AuditTrail> AuditTrails { get; set; }

    public virtual DbSet<Breeder> Breeders { get; set; }

    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<Cleaner> Cleaners { get; set; }

    public virtual DbSet<Container> Containers { get; set; }

    public virtual DbSet<ContainerRezeroDate> ContainerRezeroDates { get; set; }

    public virtual DbSet<ContainerStyle> ContainerStyles { get; set; }

    public virtual DbSet<ContainerType> ContainerTypes { get; set; }

    public virtual DbSet<Glaccount> Glaccounts { get; set; }

    public virtual DbSet<GlchemicalAccount> GlchemicalAccounts { get; set; }

    public virtual DbSet<GlgrainAccount> GlgrainAccounts { get; set; }

    public virtual DbSet<GlmiscAccount> GlmiscAccounts { get; set; }

    public virtual DbSet<GlserviceAccount> GlserviceAccounts { get; set; }

    public virtual DbSet<GltreatmentAccount> GltreatmentAccounts { get; set; }

    public virtual DbSet<GrowerField> GrowerFields { get; set; }

    public virtual DbSet<GrowerFieldCommodity> GrowerFieldCommodities { get; set; }

    public virtual DbSet<InventoryEvent> InventoryEvents { get; set; }

    public virtual DbSet<InventoryMovement> InventoryMovements { get; set; }

    public virtual DbSet<LabResult> LabResults { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Lot> Lots { get; set; }

    public virtual DbSet<LotLab> LotLabs { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Privilege> Privileges { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductClass> ProductClasses { get; set; }

    public virtual DbSet<ProductCondition> ProductConditions { get; set; }

    public virtual DbSet<ProductMeasurementUnit> ProductMeasurementUnits { get; set; }

    public virtual DbSet<ProductTrait> ProductTraits { get; set; }

    public virtual DbSet<ProductType> ProductTypes { get; set; }

    public virtual DbSet<ProductVariety> ProductVarietys { get; set; }

    public virtual DbSet<ProductVarietyItem> ProductVarietyItems { get; set; }

    public virtual DbSet<ProductVarietyItemPrice> ProductVarietyItemPrices { get; set; }

    public virtual DbSet<ProductVarietySeedColor> ProductVarietySeedColors { get; set; }

    public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }

    public virtual DbSet<PurchaseOrderLineItem> PurchaseOrderLineItems { get; set; }

    public virtual DbSet<PurchaseOrderLineItemFreightRate> PurchaseOrderLineItemFreightRates { get; set; }

    public virtual DbSet<PurchaseOrderLineItemPricing> PurchaseOrderLineItemPricings { get; set; }

    public virtual DbSet<PurchaseOrderStatusList> PurchaseOrderStatusLists { get; set; }

    public virtual DbSet<PurchaseOrderType> PurchaseOrderTypes { get; set; }

    public virtual DbSet<ReceivedGrade> ReceivedGrades { get; set; }

    public virtual DbSet<ReceivedInventoryItem> ReceivedInventoryItems { get; set; }

    public virtual DbSet<ReceivedInventoryPurchaseOrderLineItem> ReceivedInventoryPurchaseOrderLineItems { get; set; }

    public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }

    public virtual DbSet<SalesInvoiceLineItem> SalesInvoiceLineItems { get; set; }

    public virtual DbSet<SalesOrder> SalesOrders { get; set; }

    public virtual DbSet<SalesOrderLineItem> SalesOrderLineItems { get; set; }

    public virtual DbSet<SeedColor> SeedColors { get; set; }

    public virtual DbSet<SeedCommodityColor> SeedCommodityColors { get; set; }

    public virtual DbSet<SeedGroupSeedContract> SeedGroupSeedContracts { get; set; }

    public virtual DbSet<SeedVarietyColor> SeedVarietyColors { get; set; }

    public virtual DbSet<Server> Servers { get; set; }

    public virtual DbSet<Site> Sites { get; set; }

    public virtual DbSet<SiteDistrict> SiteDistricts { get; set; }

    public virtual DbSet<SiteType> SiteTypes { get; set; }

    public virtual DbSet<SitesDetail> SitesDetails { get; set; }

    public virtual DbSet<SplitGroup> SplitGroups { get; set; }

    public virtual DbSet<SplitGroupPercent> SplitGroupPercents { get; set; }

    public virtual DbSet<StorageLocation> StorageLocations { get; set; }

    public virtual DbSet<TokenCache> TokenCaches { get; set; }

    public virtual DbSet<Truck> Trucks { get; set; }

    public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }

    public virtual DbSet<UomunitType> UomunitTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserPrivilege> UserPrivileges { get; set; }

    public virtual DbSet<WeightSheet> WeightSheets { get; set; }

    public virtual DbSet<WeightSheetStatus> WeightSheetStatuses { get; set; }

    public virtual DbSet<WeightSheetType> WeightSheetTypes { get; set; }

    public virtual DbSet<WsdaTestReport> WsdaTestReports { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.ToTable("Accounts", "account");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_Active");
            entity.Property(e => e.Address1)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Address1");
            entity.Property(e => e.Address2)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Address2");
            entity.Property(e => e.AutoPrice)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_AutoPrice");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_City");
            entity.Property(e => e.Contact)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Contact");
            entity.Property(e => e.CustomerPaysRoyalties).HasAnnotation("Relational:DefaultConstraintName", "DF_Account_CustomerPaysRoyalties");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Email");
            entity.Property(e => e.EmailStatement).HasAnnotation("Relational:DefaultConstraintName", "DF_Account_EmailStatement");
            entity.Property(e => e.EntityName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.HedgedAccount).HasAnnotation("Relational:DefaultConstraintName", "DF_Account_HedgedAccount");
            entity.Property(e => e.IsProducer)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_Producer");
            entity.Property(e => e.LookupName)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_LookupName");
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_Notes");
            entity.Property(e => e.OwnerFirstName)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_OwnerFirstName");
            entity.Property(e => e.OwnerLastName)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_OwnerLastName");
            entity.Property(e => e.Phone1)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Phone1");
            entity.Property(e => e.Phone2)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Phone2");
            entity.Property(e => e.Phone3)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Phone3");
            entity.Property(e => e.PrintStatement)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_PrintStatement");
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("WA")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_State");
            entity.Property(e => e.TaxExempt).HasAnnotation("Relational:DefaultConstraintName", "DF_Account_TaxExempt");
            entity.Property(e => e.TaxExemptDate)
                .HasDefaultValue(new DateOnly(2000, 1, 1))
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Account_TaxExemptDate");
            entity.Property(e => e.Wholesale).HasAnnotation("Relational:DefaultConstraintName", "DF_Account_Wholesale");
            entity.Property(e => e.Zip)
                .IsRequired()
                .HasMaxLength(15)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Accounts_Zip");
        });

        modelBuilder.Entity<AccountCustomPricing>(entity =>
        {
            entity.ToTable("AccountCustomPricing", "account");

            entity.HasIndex(e => e.Description, "IX_AccountCustomPricing").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CustomCustomerPricing_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.Notes).HasMaxLength(255);
            entity.Property(e => e.Price)
                .HasColumnType("money")
                .HasColumnName("price");

            entity.HasOne(d => d.Account).WithMany(p => p.AccountCustomPricings)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_AccountCustomPricing_Accounts");

            entity.HasOne(d => d.Site).WithMany(p => p.AccountCustomPricings)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountCustomPricing_Sites");
        });

        modelBuilder.Entity<AlertEmail>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_alertEmails");

            entity.ToTable("AlertEmails", "system");

            entity.HasIndex(e => new { e.AlertType, e.Email }, "IX_alertEmails").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_alertEmails_UID")
                .HasColumnName("UID");
            entity.Property(e => e.AlertType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<AssignedProductClass>(entity =>
        {
            entity.ToTable("AssignedProductClasses", "product");

            entity.HasIndex(e => new { e.ProductClassId, e.ProductId }, "IX_AssignedProductClasses").IsUnique();

            entity.HasOne(d => d.ProductClass).WithMany(p => p.AssignedProductClasses)
                .HasForeignKey(d => d.ProductClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssignedProductClasses_ProductClasses");

            entity.HasOne(d => d.Product).WithMany(p => p.AssignedProductClasses)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssignedProductClasses_Products");
        });

        modelBuilder.Entity<AuditTrail>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("AuditTrail", "system");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Audit_Trail_UID")
                .HasColumnName("UID");
            entity.Property(e => e.AuditDate).HasColumnType("datetime");
            entity.Property(e => e.AuditType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.JsonString)
                .IsRequired()
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AuditTrail_JsonString");
            entity.Property(e => e.NewValue)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.OldValue)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RecordId)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("RecordID");
            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<Breeder>(entity =>
        {
            entity.ToTable("Breeders", "product");

            entity.HasIndex(e => new { e.Description, e.GlaccountId }, "IX_Breeders_Description_GlAccountId").IsUnique();

            entity.Property(e => e.Abv)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Breeders_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Breeders_Notes");

            entity.HasOne(d => d.Glaccount).WithMany(p => p.Breeders)
                .HasForeignKey(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Breeders_GLAccounts");
        });

        modelBuilder.Entity<Carrier>(entity =>
        {
            entity.ToTable("Carriers", "logistics");

            entity.HasIndex(e => e.Description, "IX_Carriers").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Cleaner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Cleaners_1");

            entity.ToTable("Cleaners", "container");

            entity.HasIndex(e => new { e.Description, e.SiteId }, "IX_Cleaners").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Cleaners_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Site).WithMany(p => p.Cleaners)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cleaners_Sites");
        });

        modelBuilder.Entity<Container>(entity =>
        {
            entity.ToTable("Containers", "container");

            entity.HasIndex(e => new { e.Description, e.StorageLocationId, e.ContainerTypeId }, "IX_Containers").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Storage_Active");
            entity.Property(e => e.Capacity).HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_Capacity");
            entity.Property(e => e.CleanerBin).HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_CleanerBin");
            entity.Property(e => e.Coordinates)
                .IsRequired()
                .HasMaxLength(250)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_Coordinates");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("(ltrim(str([container].[NextContainerAutoID]())))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_ContainerID");
            entity.Property(e => e.Destroyed).HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_Destroyed");
            entity.Property(e => e.NotForSeed).HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_SeedContainer");
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_Notes");
            entity.Property(e => e.Tare).HasAnnotation("Relational:DefaultConstraintName", "DF_Storage_Tare");
            entity.Property(e => e.Virtual).HasAnnotation("Relational:DefaultConstraintName", "DF_Containers_Virtual");

            entity.HasOne(d => d.ContainerType).WithMany(p => p.Containers)
                .HasForeignKey(d => d.ContainerTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Containers_ContainerTypes");

            entity.HasOne(d => d.StorageLocation).WithMany(p => p.Containers)
                .HasForeignKey(d => d.StorageLocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Containers_StorageLocations");
        });

        modelBuilder.Entity<ContainerRezeroDate>(entity =>
        {
            entity.ToTable("ContainerRezeroDates", "container");

            entity.Property(e => e.ZeroDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerRezeroDates_ZeroDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Container).WithMany(p => p.ContainerRezeroDates)
                .HasForeignKey(d => d.ContainerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContainerRezeroDates_Containers");
        });

        modelBuilder.Entity<ContainerStyle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ContainerStyles_1");

            entity.ToTable("ContainerStyles", "container");

            entity.HasIndex(e => e.Style, "IX_ContainerStyles").IsUnique();

            entity.HasIndex(e => e.Id, "IX_ContainerStyles_2").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Notes)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerStyles_Notes");
            entity.Property(e => e.Style)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ContainerType>(entity =>
        {
            entity.ToTable("ContainerTypes", "container");

            entity.HasIndex(e => e.Id, "IX_ContainerTypes").IsUnique();

            entity.HasIndex(e => e.Description, "IX_StorageTypes_Description").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_Active");
            entity.Property(e => e.CanRezero).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_CanRezero");
            entity.Property(e => e.DefaultCapacity)
                .HasComment("New Containers of this type will get this as the capacity")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_DefaultCapacity");
            entity.Property(e => e.DefaultTare)
                .HasComment("New Containers of this type will get this as the")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_DefaultTare");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Idx).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_idx");
            entity.Property(e => e.IsBin).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_Bin");
            entity.Property(e => e.NonSeedOnly).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_NonSeedOnly");
            entity.Property(e => e.SeedOnly).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_SeedOnly");
            entity.Property(e => e.UseForSeedReceiving).HasAnnotation("Relational:DefaultConstraintName", "DF_ContainerTypes_UseForSeedReceiving");
            entity.Property(e => e.ViewType)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("this is the base View To Use in the web page");

            entity.HasOne(d => d.ContainerStyle).WithMany(p => p.ContainerTypes)
                .HasForeignKey(d => d.ContainerStyleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContainerTypes_ContainerStyles");

            entity.HasOne(d => d.UomUnitType).WithMany(p => p.ContainerTypes)
                .HasForeignKey(d => d.UomUnitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContainerTypes_UOMUnitTypes");
        });

        modelBuilder.Entity<Glaccount>(entity =>
        {
            entity.ToTable("GLAccounts", "generalLedger");

            entity.HasIndex(e => new { e.AccountNumber, e.LocationCode }, "IX_GL_Accounts").IsUnique();

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GL_Accounts_Active");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<GlchemicalAccount>(entity =>
        {
            entity.ToTable("GLChemicalAccounts", "generalLedger");

            entity.HasIndex(e => e.GlaccountId, "IX_GLChemicalAccounts").IsUnique();

            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithOne(p => p.GlchemicalAccount)
                .HasForeignKey<GlchemicalAccount>(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GLChemicalAccounts_GLAccounts");
        });

        modelBuilder.Entity<GlgrainAccount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GLSeedAccounts");

            entity.ToTable("GLGrainAccounts", "generalLedger");

            entity.HasIndex(e => e.GlaccountId, "IX_GLGrainAccounts").IsUnique();

            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithOne(p => p.GlgrainAccount)
                .HasForeignKey<GlgrainAccount>(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GLGrainAccounts_GLAccounts");
        });

        modelBuilder.Entity<GlmiscAccount>(entity =>
        {
            entity.ToTable("GLMiscAccounts", "generalLedger");

            entity.HasIndex(e => e.GlaccountId, "IX_GLMiscAccounts").IsUnique();

            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithOne(p => p.GlmiscAccount)
                .HasForeignKey<GlmiscAccount>(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GLMiscAccounts_GLAccounts");
        });

        modelBuilder.Entity<GlserviceAccount>(entity =>
        {
            entity.ToTable("GLServiceAccounts", "generalLedger");

            entity.HasIndex(e => e.GlaccountId, "IX_GLServiceAccounts");

            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithMany(p => p.GlserviceAccounts)
                .HasForeignKey(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GLServiceAccounts_GLAccounts");
        });

        modelBuilder.Entity<GltreatmentAccount>(entity =>
        {
            entity.ToTable("GLTreatmentAccounts", "generalLedger");

            entity.HasIndex(e => e.GlaccountId, "IX_GLTreatmentAccounts").IsUnique();

            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithOne(p => p.GltreatmentAccount)
                .HasForeignKey<GltreatmentAccount>(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GLTreatmentAccounts_GLAccounts");
        });

        modelBuilder.Entity<GrowerField>(entity =>
        {
            entity.ToTable("GrowerFields", "account");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Account).WithMany(p => p.GrowerFields)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrowerFields_Accounts");
        });

        modelBuilder.Entity<GrowerFieldCommodity>(entity =>
        {
            entity.ToTable("GrowerFieldCommodity", "account");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GrowerFieldCommodity_CreationDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.GrowerField).WithMany(p => p.GrowerFieldCommodities)
                .HasForeignKey(d => d.GrowerFieldId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrowerFieldCommodity_GrowerFields");

            entity.HasOne(d => d.ProductVarietyItem).WithMany(p => p.GrowerFieldCommodities)
                .HasForeignKey(d => d.ProductVarietyItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrowerFieldCommodity_ProductVarietyItems");
        });

        modelBuilder.Entity<InventoryEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Inventor__3214EC276759737F");

            entity.ToTable("InventoryEvents", "Inventory", tb => tb.HasComment("The Type Of Movement Event "));

            entity.HasIndex(e => e.Description, "UQ__Inventor__4EBBBAC95689ADBB").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<InventoryMovement>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("InventoryMovements", "Inventory");

            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_InventoryMovementHistory_creationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Driver).HasMaxLength(255);
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.InboundQuantityBase)
                .HasComment("")
                .HasColumnType("decimal(18, 4)");
            entity.Property(e => e.InboundScaleDescription).HasMaxLength(255);
            entity.Property(e => e.InboundTime).HasColumnType("datetime");
            entity.Property(e => e.InboundWeighmaster)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.InventoryEventId).HasColumnName("InventoryEventID");
            entity.Property(e => e.Notes).HasMaxLength(255);
            entity.Property(e => e.OutboundQuantityBase)
                .HasComment("")
                .HasColumnType("decimal(18, 4)");
            entity.Property(e => e.OutboundScaleDescription).HasMaxLength(255);
            entity.Property(e => e.OutboundTime).HasColumnType("datetime");
            entity.Property(e => e.OutboundWeighmaster).HasMaxLength(255);

            entity.HasOne(d => d.InventoryEvent).WithMany()
                .HasForeignKey(d => d.InventoryEventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryMovements_InventoryEvents1");

            entity.HasOne(d => d.ReceivedInventoryItem).WithMany()
                .HasForeignKey(d => d.ReceivedInventoryItemId)
                .HasConstraintName("FK_InventoryMovements_ReceivedInventoryItems");

            entity.HasOne(d => d.Truck).WithMany()
                .HasForeignKey(d => d.TruckId)
                .HasConstraintName("FK_InventoryMovements_AccountTrucks");
        });

        modelBuilder.Entity<LabResult>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("LabResults", "Inventory");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LabResults_UID")
                .HasColumnName("UID");
            entity.Property(e => e.LabUid).HasColumnName("LabUID");
            entity.Property(e => e.Test)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Value).IsRequired();
        });

        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_SystemLog");

            entity.ToTable("Logs", "system");

            entity.Property(e => e.Uid)
                .ValueGeneratedNever()
                .HasColumnName("UID");
            entity.Property(e => e.Dbserver)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValueSql("(@@servername)")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemLog_DBServer")
                .HasColumnName("DBServer");
            entity.Property(e => e.LogType)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.TimeDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Lot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Lots_1");

            entity.ToTable("Lots", "Inventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes).IsRequired();

            entity.HasOne(d => d.ProductVarietyItem).WithMany(p => p.Lots)
                .HasForeignKey(d => d.ProductVarietyItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lots_ProductVarietyItems");

            entity.HasOne(d => d.Site).WithMany(p => p.Lots)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lots_Sites1");
        });

        modelBuilder.Entity<LotLab>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_inventoryLabs");

            entity.ToTable("LotLabs", "Inventory");

            entity.HasIndex(e => e.LabDescription, "IX_LotLabs");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LotLabs_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Closed).HasAnnotation("Relational:DefaultConstraintName", "DF_LotLabs_Closed");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LotLabs_CreationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.LabDescription)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LotLabs_ID");
            entity.Property(e => e.Quantitylbs).HasAnnotation("Relational:DefaultConstraintName", "DF_LotLabs_Quantitylbs");

            entity.HasOne(d => d.Lot).WithMany(p => p.LotLabs)
                .HasForeignKey(d => d.LotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LotLabs_Lots");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.ToTable("OrderStatus", "system");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(25);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Payments", "sale");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Payments__UID__3DB652E9")
                .HasColumnName("UID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Payments__Paymen__3EAA7722")
                .HasColumnType("datetime");
            entity.Property(e => e.ReferenceNumber).HasMaxLength(100);
            entity.Property(e => e.SalesInvoiceUid).HasColumnName("SalesInvoiceUID");

            entity.HasOne(d => d.PaymentMethodNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PaymentMethod)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_PaymentMethods");

            entity.HasOne(d => d.SalesInvoiceU).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SalesInvoiceUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_SalesInvoices");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.ToTable("PaymentMethods", "sale");

            entity.HasIndex(e => e.TypeOfPayment, "IX_PaymentTypes").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.TypeOfPayment)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Privilege>(entity =>
        {
            entity.ToTable("Privileges", "users");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GL_Items");

            entity.ToTable("Products", "product");

            entity.HasIndex(e => new { e.Description, e.GlaccountId }, "IX_Products").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_Active");
            entity.Property(e => e.CanUseScale)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_CanUseScale");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");
            entity.Property(e => e.Hidden).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_Hidden");
            entity.Property(e => e.Notes)
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_@Notes");
            entity.Property(e => e.ReceiveableItem)
                .HasDefaultValue(true)
                .HasComment("You Cannot Receive a Service like Delivery Fee")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_CanReceiveItem");

            entity.HasOne(d => d.DefaultCondition).WithMany(p => p.Products)
                .HasForeignKey(d => d.DefaultConditionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_ProductConditions");

            entity.HasOne(d => d.DefaultUom).WithMany(p => p.Products)
                .HasForeignKey(d => d.DefaultUomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_UnitOfMeasures");

            entity.HasOne(d => d.Glaccount).WithMany(p => p.Products)
                .HasForeignKey(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_GLAccounts");
        });

        modelBuilder.Entity<ProductClass>(entity =>
        {
            entity.ToTable("ProductClasses", "product");

            entity.HasIndex(e => new { e.Description, e.GlaccountId }, "IX_ProductClasses_Description_GlAccountId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");

            entity.HasOne(d => d.Glaccount).WithMany(p => p.ProductClasses)
                .HasForeignKey(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductClasses_GLAccounts");
        });

        modelBuilder.Entity<ProductCondition>(entity =>
        {
            entity.ToTable("ProductConditions", "product");

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductConditions_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.GlaccountId).HasColumnName("GLAccountId");
            entity.Property(e => e.Locked).HasAnnotation("Relational:DefaultConstraintName", "DF_ProductConditions_Locked");
            entity.Property(e => e.RequireLot).HasAnnotation("Relational:DefaultConstraintName", "DF_ProductConditions_RequireLot");

            entity.HasOne(d => d.Glaccount).WithMany(p => p.ProductConditions)
                .HasForeignKey(d => d.GlaccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductConditions_GLAccounts");
        });

        modelBuilder.Entity<ProductMeasurementUnit>(entity =>
        {
            entity.ToTable("ProductMeasurementUnits", "product");

            entity.HasIndex(e => new { e.GlAccountId, e.UomId }, "IX_ProductMeasurementUnits").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DefaultUom).HasAnnotation("Relational:DefaultConstraintName", "DF_GLAccountUOM_DefaultUnit");

            entity.HasOne(d => d.GlAccount).WithMany(p => p.ProductMeasurementUnits)
                .HasForeignKey(d => d.GlAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductMeasurementUnits_GLAccounts");

            entity.HasOne(d => d.Uom).WithMany(p => p.ProductMeasurementUnits)
                .HasForeignKey(d => d.UomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductMeasurementUnits_UnitOfMeasures");
        });

        modelBuilder.Entity<ProductTrait>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_SeedTraits");

            entity.ToTable("ProductTraits", "product");

            entity.HasIndex(e => new { e.Description, e.ProductId }, "IX_ProductTraits").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductTraits_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes).HasMaxLength(255);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductTraits)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductTraits_Products");
        });

        modelBuilder.Entity<ProductType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GL_ItemType");

            entity.ToTable("ProductTypes", "product");

            entity.HasIndex(e => new { e.Description, e.ProductId }, "IX_ProductTypes_1").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductTypes_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MarketPrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductTypes_MarketPrice")
                .HasColumnType("money");
            entity.Property(e => e.MarketPriceDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductTypes_MarketPriceDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductTypes)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductTypes_Products");
        });

        modelBuilder.Entity<ProductVariety>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ProductVariety");

            entity.ToTable("ProductVarietys", "product");

            entity.HasIndex(e => e.Description, "IX_ProductVarietys").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietys_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietys_Notes");

            entity.HasOne(d => d.Breeder).WithMany(p => p.ProductVarieties)
                .HasForeignKey(d => d.BreederId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietys_Breeders");

            entity.HasOne(d => d.ProductTrait).WithMany(p => p.ProductVarieties)
                .HasForeignKey(d => d.ProductTraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietys_ProductTraits");

            entity.HasOne(d => d.ProductType).WithMany(p => p.ProductVarieties)
                .HasForeignKey(d => d.ProductTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietys_ProductTypes");
        });

        modelBuilder.Entity<ProductVarietyItem>(entity =>
        {
            entity.ToTable("ProductVarietyItems", "product");

            entity.HasIndex(e => e.Description, "IX_ProductVarietyItems").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_Active");
            entity.Property(e => e.AutoPrice)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_AutoPrice");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_Notes");
            entity.Property(e => e.PurchaseCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_PurchaseCode");
            entity.Property(e => e.RequireGrowerField)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_RequireGrowerField");
            entity.Property(e => e.Royalty)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_Royalty")
                .HasColumnType("money");
            entity.Property(e => e.SalesCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietyItem_SalesCode");

            entity.HasOne(d => d.ProductClass).WithMany(p => p.ProductVarietyItems)
                .HasForeignKey(d => d.ProductClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietyItems_ProductClasses");

            entity.HasOne(d => d.ProductCondition).WithMany(p => p.ProductVarietyItems)
                .HasForeignKey(d => d.ProductConditionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietyItems_ProductConditions");

            entity.HasOne(d => d.ProductVariety).WithMany(p => p.ProductVarietyItems)
                .HasForeignKey(d => d.ProductVarietyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietyItems_ProductVarietys");
        });

        modelBuilder.Entity<ProductVarietyItemPrice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ProductVarietyItemPrices_1");

            entity.ToTable("ProductVarietyItemPrices", "product");

            entity.HasIndex(e => new { e.SiteId, e.ProductVarietyItemId }, "IX_ProductVarietyItemPrices").IsUnique();

            entity.Property(e => e.CleaningFee)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_CleaningFee")
                .HasColumnType("money");
            entity.Property(e => e.RetailPrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_RetailPrice")
                .HasColumnType("money");
            entity.Property(e => e.ScreeningPrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_ScreeningPrice")
                .HasColumnType("money");
            entity.Property(e => e.ScreeningPriceDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_ScreeningPriceDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ScreeningsPercent)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_ScreeningsPercent")
                .HasColumnType("decimal(6, 4)");
            entity.Property(e => e.WholesalePrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Gl_ItemSitePrice_WholesalePrice")
                .HasColumnType("money");

            entity.HasOne(d => d.ProductVarietyItem).WithMany(p => p.ProductVarietyItemPrices)
                .HasForeignKey(d => d.ProductVarietyItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietyItemPrices_ProductVarietyItems");

            entity.HasOne(d => d.Site).WithMany(p => p.ProductVarietyItemPrices)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVarietyItemPrices_Sites");
        });

        modelBuilder.Entity<ProductVarietySeedColor>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_ProductVarietySeedColor");

            entity.ToTable("ProductVarietySeedColors", "product");

            entity.HasIndex(e => new { e.ProductTypeUid, e.ColorIndex }, "IX_ProductVarietySeedColor").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductVarietySeedColor_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ProductTypeUid).HasColumnName("ProductTypeUID");
        });

        modelBuilder.Entity<PurchaseOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PurchaseOrder");

            entity.ToTable("PurchaseOrders", "purchase");

            entity.HasIndex(e => e.Id, "IX_PurchaseOrders").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerReference).IsRequired();
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.ParentPurchaseOrderId).HasColumnName("ParentPurchaseOrderID");
            entity.Property(e => e.PurchaseOrderTypeId).HasColumnName("PurchaseOrderTypeID");
            entity.Property(e => e.StatusId)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrders_StatusId");

            entity.HasOne(d => d.Account).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_Accounts");

            entity.HasOne(d => d.ParentPurchaseOrder).WithMany(p => p.InverseParentPurchaseOrder)
                .HasForeignKey(d => d.ParentPurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_PurchaseOrders3");

            entity.HasOne(d => d.PurchaseOrderType).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.PurchaseOrderTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_PurchaseOrderType");

            entity.HasOne(d => d.Site).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_DbServers");

            entity.HasOne(d => d.Status).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_OrderStatus");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrders_PurchaseOrderStatusLists");
        });

        modelBuilder.Entity<PurchaseOrderLineItem>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_PurchaseOrderLineItem");

            entity.ToTable("PurchaseOrderLineItems", "purchase");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLineItems_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Acres).HasColumnType("decimal(10, 1)");
            entity.Property(e => e.AmountBase).HasColumnType("decimal(20, 4)");
            entity.Property(e => e.CustomerReference).IsRequired();
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.Preimum).HasColumnType("money");
            entity.Property(e => e.PurchaseOrderId).HasColumnName("PurchaseOrderID");
            entity.Property(e => e.StateCleanout).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.StateDockage).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.YieldLbs).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Lot).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.LotId)
                .HasConstraintName("FK_PurchaseOrderLineItems_Lots");

            entity.HasOne(d => d.ProductVarietyItem).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.ProductVarietyItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItems_ProductVarietyItems");

            entity.HasOne(d => d.PurchaseOrder).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.PurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItems_PurchaseOrders");

            entity.HasOne(d => d.Status).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItems_OrderStatus");

            entity.HasOne(d => d.UnitOfMeasure).WithMany(p => p.PurchaseOrderLineItems)
                .HasForeignKey(d => d.UnitOfMeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItems_UnitOfMeasures");
        });

        modelBuilder.Entity<PurchaseOrderLineItemFreightRate>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_SeedContractFreightRate");

            entity.ToTable("PurchaseOrderLineItemFreightRates", "purchase");

            entity.HasIndex(e => new { e.Description, e.PurchaseOrderLineItemUid }, "IX_SeedContractFreightRates");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedContractFreightRates_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedContractFreightRates_Notes");
            entity.Property(e => e.PurchaseOrderLineItemUid).HasColumnName("PurchaseOrderLineItemUID");

            entity.HasOne(d => d.PurchaseOrderLineItemU).WithMany(p => p.PurchaseOrderLineItemFreightRates)
                .HasForeignKey(d => d.PurchaseOrderLineItemUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItemFreightRates_PurchaseOrderLineItems");

            entity.HasOne(d => d.Site).WithMany(p => p.PurchaseOrderLineItemFreightRates)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItemFreightRates_Sites");

            entity.HasOne(d => d.Uom).WithMany(p => p.PurchaseOrderLineItemFreightRates)
                .HasForeignKey(d => d.UomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItemFreightRates_UnitOfMeasures");
        });

        modelBuilder.Entity<PurchaseOrderLineItemPricing>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("PurchaseOrderLineItemPricing", "purchase");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLineItemPricing_UID")
                .HasColumnName("UID");
            entity.Property(e => e.BaseAmount).HasColumnType("decimal(20, 4)");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLineItemPricing_CreationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.NetPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PurchaseOrderLineItemUid).HasColumnName("PurchaseOrderLineItemUID");

            entity.HasOne(d => d.PurchaseOrderLineItemU).WithMany(p => p.PurchaseOrderLineItemPricings)
                .HasForeignKey(d => d.PurchaseOrderLineItemUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrderLineItemPricing_PurchaseOrderLineItems");
        });

        modelBuilder.Entity<PurchaseOrderStatusList>(entity =>
        {
            entity.ToTable("PurchaseOrderStatusLists", "purchase");

            entity.HasIndex(e => e.Description, "IX_PurchaseOrderStatusLists").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(25);
        });

        modelBuilder.Entity<PurchaseOrderType>(entity =>
        {
            entity.ToTable("PurchaseOrderType", "purchase");

            entity.HasIndex(e => e.Description, "IX_PurchaseOrderType").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(25);
        });

        modelBuilder.Entity<ReceivedGrade>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("ReceivedGrades", "seed");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ReceivedGrades_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ReceiveScaleTicketUid).HasColumnName("ReceiveScaleTicketUID");
            entity.Property(e => e.Test)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Value).IsRequired();
        });

        modelBuilder.Entity<ReceivedInventoryItem>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_RecievedInventoryItems");

            entity.ToTable("ReceivedInventoryItems", "purchase");

            entity.Property(e => e.Uid)
                .ValueGeneratedNever()
                .HasColumnName("UID");
            entity.Property(e => e.Bol)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CustomerReference).HasMaxLength(255);
            entity.Property(e => e.Notes).HasMaxLength(255);
            entity.Property(e => e.RecievedInventoryPurchaseOrderLineItemUid).HasColumnName("RecievedInventoryPurchaseOrderLineItemUID");
            entity.Property(e => e.WeightSheetUid).HasColumnName("WeightSheetUID");

            entity.HasOne(d => d.RecievedInventoryPurchaseOrderLineItemU).WithMany(p => p.ReceivedInventoryItems)
                .HasForeignKey(d => d.RecievedInventoryPurchaseOrderLineItemUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivedInventoryItems_ReceivedInventoryPurchaseOrderLineItems");
        });

        modelBuilder.Entity<ReceivedInventoryPurchaseOrderLineItem>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_ReceivedInventoyrPurchaseOrders");

            entity.ToTable("ReceivedInventoryPurchaseOrderLineItems", "purchase");

            entity.Property(e => e.Uid)
                .ValueGeneratedNever()
                .HasColumnName("UID");
            entity.Property(e => e.PurchaseOrderLineItemUid).HasColumnName("PurchaseOrderLineItemUID");

            entity.HasOne(d => d.PurchaseOrderLineItemU).WithMany(p => p.ReceivedInventoryPurchaseOrderLineItems)
                .HasForeignKey(d => d.PurchaseOrderLineItemUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivedInventoryPurchaseOrderLineItems_PurchaseOrderLineItems");
        });

        modelBuilder.Entity<SalesInvoice>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SalesInvoices", "sale");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalesInvoices_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Contact).HasMaxLength(255);
            entity.Property(e => e.ContactEmail).HasMaxLength(50);
            entity.Property(e => e.ContactPhone).HasMaxLength(20);
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalesInvoices_CreationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerReference).HasMaxLength(255);
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ReturnedScalesOrderUid).HasColumnName("ReturnedScalesOrderUID");
            entity.Property(e => e.SalesOrderReferenceUid).HasColumnName("SalesOrderReferenceUID");
            entity.Property(e => e.ShipToAddress).HasMaxLength(255);
            entity.Property(e => e.ShipToCity).HasMaxLength(255);
            entity.Property(e => e.ShipToState).HasMaxLength(50);
            entity.Property(e => e.ShipToZip).HasMaxLength(15);
            entity.Property(e => e.SiteId).HasColumnName("SiteID");

            entity.HasOne(d => d.Account).WithMany(p => p.SalesInvoices)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesInvoices_Accounts");

            entity.HasOne(d => d.Carrier).WithMany(p => p.SalesInvoices)
                .HasForeignKey(d => d.CarrierId)
                .HasConstraintName("FK_SalesInvoices_Carriers");
        });

        modelBuilder.Entity<SalesInvoiceLineItem>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SalesInvoiceLineItems", "sale");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalesInvoiceLineItems_UID")
                .HasColumnName("UID");
            entity.Property(e => e.InventoryMovementUid).HasColumnName("InventoryMovementUID");
            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.SalesInvoiceUid).HasColumnName("SalesInvoiceUID");
            entity.Property(e => e.SalesOrderLineItemUid).HasColumnName("SalesOrderLineItemUID");

            entity.HasOne(d => d.UidNavigation).WithOne(p => p.SalesInvoiceLineItem)
                .HasForeignKey<SalesInvoiceLineItem>(d => d.Uid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesInvoiceLineItems_SalesInvoices");
        });

        modelBuilder.Entity<SalesOrder>(entity =>
        {
            entity.ToTable("SalesOrders", "sale");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Contact).HasMaxLength(255);
            entity.Property(e => e.ContactEmail).HasMaxLength(50);
            entity.Property(e => e.ContactPhone).HasMaxLength(20);
            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerReference).HasMaxLength(255);
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.ShipToAddress).HasMaxLength(255);
            entity.Property(e => e.ShipToCity).HasMaxLength(255);
            entity.Property(e => e.ShipToState).HasMaxLength(50);
            entity.Property(e => e.ShipToZip).HasMaxLength(15);
            entity.Property(e => e.SiteId).HasColumnName("SiteID");

            entity.HasOne(d => d.Account).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrders_Accounts");

            entity.HasOne(d => d.Carrier).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.CarrierId)
                .HasConstraintName("FK_SalesOrders_Carriers");
        });

        modelBuilder.Entity<SalesOrderLineItem>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SalesOrderLineItems", "sale");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalesOrderLineItems_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.ProductVarietyItemUid).HasColumnName("ProductVarietyItemUID");
            entity.Property(e => e.QuantityBaseAmount).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderLineItems)
                .HasForeignKey(d => d.SalesOrderId)
                .HasConstraintName("FK_SalesOrderLineItems_SalesOrders");
        });

        modelBuilder.Entity<SeedColor>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SeedColors", "seed");

            entity.HasIndex(e => e.Id, "IX_SeedColors").IsUnique();

            entity.HasIndex(e => e.HexValue, "IX_SeedColors_1").IsUnique();

            entity.HasIndex(e => e.Description, "IX_SeedColors_2").IsUnique();

            entity.HasIndex(e => e.ClassName, "IX_SeedColors_3").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedColors_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ClassName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.HexValue)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Id).HasColumnName("ID");
        });

        modelBuilder.Entity<SeedCommodityColor>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_SeedCommdityColors");

            entity.ToTable("SeedCommodityColors", "seed");

            entity.HasIndex(e => e.ProductUid, "IX_SeedCommdityColors").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedCommdityColors_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ColorIndex).HasAnnotation("Relational:DefaultConstraintName", "DF_SeedCommdityColors_ColorIndex");
            entity.Property(e => e.ProductUid).HasColumnName("ProductUID");

            entity.HasOne(d => d.ColorIndexNavigation).WithMany(p => p.SeedCommodityColors)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ColorIndex)
                .HasConstraintName("FK_SeedCommdityColors_SeedColors");
        });

        modelBuilder.Entity<SeedGroupSeedContract>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SeedGroupSeedContracts", "seed");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedGroupSeedContracts_UID")
                .HasColumnName("UID");
            entity.Property(e => e.SeedContractUid).HasColumnName("SeedContractUID");
            entity.Property(e => e.SeedGroupUid).HasColumnName("SeedGroupUID");
        });

        modelBuilder.Entity<SeedVarietyColor>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("SeedVarietyColors", "seed");

            entity.Property(e => e.Uid)
                .ValueGeneratedNever()
                .HasColumnName("UID");
            entity.Property(e => e.ColorIndex).HasAnnotation("Relational:DefaultConstraintName", "DF_SeedVarietyColors_ColorIndex");
            entity.Property(e => e.SecondsOff).HasAnnotation("Relational:DefaultConstraintName", "DF_SeedVarietyColors_SecondsOn1");
            entity.Property(e => e.SecondsOn).HasAnnotation("Relational:DefaultConstraintName", "DF_SeedVarietyColors_SecondsOn");
            entity.Property(e => e.VarietyUid).HasColumnName("VarietyUID");

            entity.HasOne(d => d.ColorIndexNavigation).WithMany(p => p.SeedVarietyColors)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ColorIndex)
                .HasConstraintName("FK_SeedVarietyColors_SeedColors");
        });

        modelBuilder.Entity<Server>(entity =>
        {
            entity.ToTable("Servers", "system");

            entity.HasIndex(e => e.Id, "IX_Servers_ID").IsUnique();

            entity.HasIndex(e => e.ServerName, "IX_Servers_Name").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ServerName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Site>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Locations");

            entity.ToTable("Sites", "system");

            entity.HasIndex(e => e.Description, "IX_Locations_Description").IsUnique();

            entity.HasIndex(e => e.Id, "IX_Sites").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_Active");
            entity.Property(e => e.Address1)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_Address1");
            entity.Property(e => e.Address2)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_Address2");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_City");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(25)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_Phone");
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_State");
            entity.Property(e => e.TypeId).HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_SeedPlant");
            entity.Property(e => e.Zip)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Sites_Zip");
        });

        modelBuilder.Entity<SiteDistrict>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_DistrictId");

            entity.ToTable("SiteDistricts", "system");

            entity.HasIndex(e => e.Description, "IX_SiteDistricts").IsUnique();

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<SiteType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_SiteTypeId");

            entity.ToTable("SiteTypes", "system");

            entity.HasIndex(e => e.Description, "IX_SiteTypes").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<SitesDetail>(entity =>
        {
            entity.ToTable("SitesDetails", "seed");

            entity.HasIndex(e => e.SiteId, "IX_SitesDetails").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SitesDetails_Active");
            entity.Property(e => e.CertFeePerLb)
                .HasDefaultValue(0.0028m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SitesDetails_CertFeePerLb")
                .HasColumnType("money");
            entity.Property(e => e.DefaultCleaningFee)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SitesDetails_CleaningFee")
                .HasColumnType("money");
            entity.Property(e => e.DefaultScreeningsPercent)
                .HasDefaultValue(0.05m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SitesDetails_DefaultScreeningsPercent")
                .HasColumnType("decimal(6, 4)");

            entity.HasOne(d => d.InHouseAccount).WithMany(p => p.SitesDetails)
                .HasForeignKey(d => d.InHouseAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SitesDetails_Accounts");
        });

        modelBuilder.Entity<SplitGroup>(entity =>
        {
            entity.ToTable("SplitGroups", "account");

            entity.HasIndex(e => e.SplitGroupNumber, "IX_SplitGroups_1");

            entity.HasIndex(e => e.Description, "IX_SplitGroups_2");

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountGroups_Active");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UseForReceive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountGroups_UseForReceive");
            entity.Property(e => e.UseForSales)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AccountGroups_UseForSales");

            entity.HasOne(d => d.PrimaryAccount).WithMany(p => p.SplitGroups)
                .HasForeignKey(d => d.PrimaryAccountId)
                .HasConstraintName("FK_SplitGroups_Accounts");
        });

        modelBuilder.Entity<SplitGroupPercent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SplitGroupPrecents");

            entity.ToTable("SplitGroupPercents", "account");

            entity.HasIndex(e => new { e.SplitGroupId, e.AccountId }, "IX_SplitGroupPercents").IsUnique();

            entity.Property(e => e.SplitPercent).HasColumnType("decimal(10, 7)");

            entity.HasOne(d => d.Account).WithMany(p => p.SplitGroupPercents)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_SplitGroupPrecents_Accounts");

            entity.HasOne(d => d.SplitGroup).WithMany(p => p.SplitGroupPercents)
                .HasForeignKey(d => d.SplitGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SplitGroupPercents_SplitGroups");
        });

        modelBuilder.Entity<StorageLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_StorageLocations_1");

            entity.ToTable("StorageLocations", "container");

            entity.HasIndex(e => new { e.Description, e.SiteId }, "IX_StorageLocations").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SiteLocations_Active");
            entity.Property(e => e.Coordinates)
                .IsRequired()
                .HasMaxLength(250)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StorageLocations_Coordinates");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Notes)
                .IsRequired()
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StorageLocations_Notes");
        });

        modelBuilder.Entity<TokenCache>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TokenCac__3214EC07FAA0762C");

            entity.ToTable("TokenCache", "web");

            entity.Property(e => e.Id).HasMaxLength(449);
            entity.Property(e => e.Value).IsRequired();
        });

        modelBuilder.Entity<Truck>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_Trucks_1");

            entity.ToTable("Trucks", "account");

            entity.HasIndex(e => new { e.CarrierId, e.Description }, "UX_Truck_Carrier_Description")
                .IsUnique()
                .HasFilter("([CarrierId] IS NOT NULL)");

            entity.HasIndex(e => e.RfidTag, "UX_Trucks_RfidTag_NotEmpty")
                .IsUnique()
                .HasFilter("([RfidTag]<>'')");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_UID_1")
                .HasColumnName("UID");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_Active_1");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ParentTruckUid)
                .HasComment("If this was a pup to a truck then the parent truck would be another truck UID otherwise the same UID")
                .HasColumnName("ParentTruckUID");
            entity.Property(e => e.RetainTare)
                .HasComment("if true the tare is kept and reused ")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_RetainTare");
            entity.Property(e => e.RfidTag)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_RfidTag");
            entity.Property(e => e.Tare)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_Tare")
                .HasColumnType("decimal(10, 4)");
            entity.Property(e => e.TruckIndex)
                .HasDefaultValue(1)
                .HasComment("This would be the order of the truck and pups so ParentTruck - then Pup ...")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trucks_TruckIndex");

            entity.HasOne(d => d.Account).WithMany(p => p.Trucks)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_AccountTrucks_Accounts");

            entity.HasOne(d => d.Carrier).WithMany(p => p.Trucks)
                .HasForeignKey(d => d.CarrierId)
                .HasConstraintName("FK_Trucks_Carriers");
        });

        modelBuilder.Entity<UnitOfMeasure>(entity =>
        {
            entity.ToTable("UnitOfMeasures", "system");

            entity.HasIndex(e => e.Description, "IX_UnitOfMeasure").IsUnique();

            entity.HasIndex(e => e.Unit, "IX_UnitOfMeasure_Abv").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UnitOfMeasures_Active");
            entity.Property(e => e.ConversionFactor)
                .HasDefaultValue(1m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UnitOfMeasures_Multliplier")
                .HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PricePrecision)
                .HasDefaultValue(2)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UnitOfMeasure_PricePercesion");
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UnitsPrecision).HasAnnotation("Relational:DefaultConstraintName", "DF_UnitOfMeasure_Precision");

            entity.HasOne(d => d.UomType).WithMany(p => p.UnitOfMeasures)
                .HasForeignKey(d => d.UomTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UnitOfMeasures_UOMUnitTypes");
        });

        modelBuilder.Entity<UomunitType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UOMUnitType");

            entity.ToTable("UOMUnitTypes", "system");

            entity.HasIndex(e => e.Description, "IX_UOMUnitType").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BaseUnitsName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CanUseScale).HasAnnotation("Relational:DefaultConstraintName", "DF_UOMUnitTypes_CanUseScale");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Users_1");

            entity.ToTable("Users", "users");

            entity.HasIndex(e => e.Name, "IX_UserName").IsUnique();

            entity.HasIndex(e => e.UserPin, "IX_UserPin").IsUnique();

            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_Active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<UserPrivilege>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UserPrivileges_1");

            entity.ToTable("UserPrivileges", "users");

            entity.HasOne(d => d.Privilege).WithMany(p => p.UserPrivileges)
                .HasForeignKey(d => d.PrivilegeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivileges_Privileges");

            entity.HasOne(d => d.User).WithMany(p => p.UserPrivileges)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivileges_Users");
        });

        modelBuilder.Entity<WeightSheet>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("WeightSheet", "purchase");

            entity.HasIndex(e => new { e.Id, e.SiteId }, "IX_WeightSheet").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WeightSheet_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.InternalNotes).IsRequired();
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.SiteId).HasColumnName("SiteID");
            entity.Property(e => e.StatusId)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WeightSheet_StatusId");

            entity.HasOne(d => d.Site).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WeightSheet_Sites");

            entity.HasOne(d => d.Status).WithMany(p => p.WeightSheets)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WeightSheet_WeightSheetStatus");
        });

        modelBuilder.Entity<WeightSheetStatus>(entity =>
        {
            entity.ToTable("WeightSheetStatus", "purchase");

            entity.HasIndex(e => e.Description, "IX_WeightSheetStatus").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<WeightSheetType>(entity =>
        {
            entity.ToTable("WeightSheetTypes", "purchase");

            entity.HasIndex(e => e.Description, "IX_WeightSheetTypes").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<WsdaTestReport>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_WSDA");

            entity.ToTable("WsdaTestReports", "seed");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WSDA_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ComponentType).HasMaxLength(255);
            entity.Property(e => e.LabNumber)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.LotNumber)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TestName).HasMaxLength(255);
            entity.Property(e => e.TestValue).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Units).HasMaxLength(50);
            entity.Property(e => e.Variety)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}