// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class PurchaseOrderLineItemFreightRate
{
    public Guid Uid { get; set; }

    public Guid PurchaseOrderLineItemUid { get; set; }

    public int SiteId { get; set; }

    public int UomId { get; set; }

    public string Notes { get; set; }

    public string Description { get; set; }

    public bool Active { get; set; }

    public virtual PurchaseOrderLineItem PurchaseOrderLineItemU { get; set; }

    public virtual Site Site { get; set; }

    public virtual UnitOfMeasure Uom { get; set; }
}