// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class PurchaseOrderLineItemPricing
{
    public Guid Uid { get; set; }

    public Guid PurchaseOrderLineItemUid { get; set; }

    public DateTime CreationDate { get; set; }

    public decimal BaseAmount { get; set; }

    public decimal NetPrice { get; set; }

    public string Notes { get; set; }

    public virtual PurchaseOrderLineItem PurchaseOrderLineItemU { get; set; }
}