// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class SitesDetail
{
    public int Id { get; set; }

    public int SiteId { get; set; }

    public decimal DefaultCleaningFee { get; set; }

    public decimal DefaultScreeningsPercent { get; set; }

    public long InHouseAccountId { get; set; }

    public bool Active { get; set; }

    public decimal CertFeePerLb { get; set; }

    public virtual Account InHouseAccount { get; set; }
}