// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class UserPrivilege
{
    public Guid Uid { get; set; }

    public int PrivilegeId { get; set; }

    public Guid UserUid { get; set; }

    public virtual Privilege Privilege { get; set; }

    public virtual User UserU { get; set; }
}