// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Agvantage_Transfer.NwModels;

public partial class NW_DataContext : DbContext
{
    public NW_DataContext()
    {
    }

    public NW_DataContext(DbContextOptions<NW_DataContext> options)
        : base(options)
    {
    }

   
    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<Crop> Crops { get; set; }

    public virtual DbSet<Producer> Producers { get; set; }

  
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       

        modelBuilder.Entity<Carrier>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_DE9C152F786D494C850B84765A6DA733");
                    tb.HasTrigger("MSmerge_ins_DE9C152F786D494C850B84765A6DA733");
                    tb.HasTrigger("MSmerge_upd_DE9C152F786D494C850B84765A6DA733");
                });

            entity.HasIndex(e => e.Id, "IX_Carriers").IsUnique();

            entity.HasIndex(e => e.Description, "IX_Carriers_Description").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("UID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Crop>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_1DA0B0307B4D4CB7B09C8B5B78FA6C4A");
                    tb.HasTrigger("MSmerge_ins_1DA0B0307B4D4CB7B09C8B5B78FA6C4A");
                    tb.HasTrigger("MSmerge_upd_1DA0B0307B4D4CB7B09C8B5B78FA6C4A");
                });

            entity.HasIndex(e => e.Description, "IX_Crops_Description").IsUnique();

            entity.HasIndex(e => e.Id, "IX_Crops_Id").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("UID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.ColorIndex).HasColumnName("Color_Index");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PoundPerBushel)
                .HasDefaultValue(60f)
                .HasColumnName("Pound_Per_Bushel");
            entity.Property(e => e.SecondaryColorIndex).HasColumnName("Secondary_Color_Index");
            entity.Property(e => e.UnitOfMeasure)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("bu")
                .IsFixedLength()
                .HasColumnName("Unit_Of_Measure");
            entity.Property(e => e.UseAtElevator).HasColumnName("Use_At_Elevator");
            entity.Property(e => e.UseAtSeedMill).HasColumnName("Use_At_Seed_Mill");
        });

        modelBuilder.Entity<Producer>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_C33B3B3FE0984DCB97E23DBC948B9030");
                    tb.HasTrigger("MSmerge_ins_C33B3B3FE0984DCB97E23DBC948B9030");
                    tb.HasTrigger("MSmerge_upd_C33B3B3FE0984DCB97E23DBC948B9030");
                });

            entity.HasIndex(e => e.Id, "IX_Producers").IsUnique();

            entity.HasIndex(e => e.Description, "IX_Producers_1").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("UID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Address1).HasMaxLength(255);
            entity.Property(e => e.Address2).HasMaxLength(255);
            entity.Property(e => e.City).HasMaxLength(255);
            entity.Property(e => e.CompanyName)
                .HasMaxLength(255)
                .HasColumnName("Company_Name");
            entity.Property(e => e.CustomerName1)
                .HasMaxLength(255)
                .HasColumnName("Customer_Name1");
            entity.Property(e => e.CustomerName2)
                .HasMaxLength(255)
                .HasColumnName("Customer_Name2");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EmailAddress)
                .HasMaxLength(255)
                .HasColumnName("Email_Address");
            entity.Property(e => e.EmailWs).HasColumnName("Email_WS");
            entity.Property(e => e.HomePhone)
                .HasMaxLength(16)
                .HasColumnName("Home_Phone");
            entity.Property(e => e.Member).HasMaxLength(10);
            entity.Property(e => e.MobilePhone)
                .HasMaxLength(16)
                .HasColumnName("Mobile_Phone");
            entity.Property(e => e.Phone).HasMaxLength(16);
            entity.Property(e => e.PrintWs)
                .HasDefaultValue(true)
                .HasColumnName("Print_WS");
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.WorkPhone)
                .HasMaxLength(16)
                .HasColumnName("Work_Phone");
            entity.Property(e => e.Zip1).HasMaxLength(20);
            entity.Property(e => e.Zip2).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}