// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Agvantage_TransferV2.SeedModels;

public partial class AgvantageSeedDepartmentDTO
{
    public Guid Uid { get; set; }

    public int Id { get; set; }

    public string Description { get; set; }

    public bool SpringWheat { get; set; }

    public bool NotUsed { get; set; }
}