// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpdateZipCodes.Models;

public partial class ZipCode
{
    public Guid Uid { get; set; }

    public string State { get; set; }

    public string County { get; set; }

    public string Zip { get; set; }
}