// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Seed25.Models;

public partial class BinArea
{
    public Guid Uid { get; set; }

    public int LocationId { get; set; }

    public string Area { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();
}