// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Seed25.Models;

public partial class ItemLocation
{
    public Guid Uid { get; set; }

    public int Id { get; set; }

    public int LocationId { get; set; }

    public decimal Price { get; set; }

    public bool Inactive { get; set; }

    public bool NotInUse { get; set; }

    public string Lot { get; set; }

    public string Comment { get; set; }

    public decimal? DefaultValue { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();
}