// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Seed25.Models;

public partial class Seed_DataContext : DbContext
{
    public Seed_DataContext()
    {
    }

    public Seed_DataContext(DbContextOptions<Seed_DataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bin> Bins { get; set; }

    public virtual DbSet<BinArea> BinAreas { get; set; }

    public virtual DbSet<BinColor> BinColors { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemLocation> ItemLocations { get; set; }

    public virtual DbSet<ItemType> ItemTypes { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Lot> Lots { get; set; }

    public virtual DbSet<LotAnalysis> LotAnalyses { get; set; }

    public virtual DbSet<PcAllowedToPrint> PcAllowedToPrints { get; set; }

    public virtual DbSet<ScaleCamera> ScaleCameras { get; set; }

    public virtual DbSet<SeedDepartment> SeedDepartments { get; set; }

    public virtual DbSet<SeedTicket> SeedTickets { get; set; }

    public virtual DbSet<SeedTicketMisc> SeedTicketMiscs { get; set; }

    public virtual DbSet<SeedTicketTreatment> SeedTicketTreatments { get; set; }

    public virtual DbSet<SeedTicketVariety> SeedTicketVarieties { get; set; }

    public virtual DbSet<SeedTicketWeight> SeedTicketWeights { get; set; }

    public virtual DbSet<SeedTrait> SeedTraits { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<Trait> Traits { get; set; }

    public virtual DbSet<TreatmentWeight> TreatmentWeights { get; set; }

  
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bin>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_Bin_UID");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_0FEAB7E4BDBF48DC915388245514354F");
                    tb.HasTrigger("MSmerge_ins_0FEAB7E4BDBF48DC915388245514354F");
                    tb.HasTrigger("MSmerge_upd_0FEAB7E4BDBF48DC915388245514354F");
                });

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Bins_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Bins_Inactive");
            entity.Property(e => e.AreaUid).HasColumnName("Area_UID");
            entity.Property(e => e.Bushels).HasAnnotation("Relational:DefaultConstraintName", "DF_Bins_Bushels");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ItemLocationUid).HasColumnName("Item_Location_UID");
            entity.Property(e => e.Lot).HasMaxLength(100);

            entity.HasOne(d => d.AreaU).WithMany(p => p.Bins)
                .HasForeignKey(d => d.AreaUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bins_BinAreas");

            entity.HasOne(d => d.ItemLocationU).WithMany(p => p.Bins)
                .HasForeignKey(d => d.ItemLocationUid)
                .HasConstraintName("FK_Bins_Item_Location");
        });

        modelBuilder.Entity<BinArea>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_BinAreas");

            entity.ToTable("Bin_Areas", tb =>
                {
                    tb.HasTrigger("MSmerge_del_8962E537722949FCB07BA55DCE3012B2");
                    tb.HasTrigger("MSmerge_ins_8962E537722949FCB07BA55DCE3012B2");
                    tb.HasTrigger("MSmerge_upd_8962E537722949FCB07BA55DCE3012B2");
                });

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BinAreas_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Area)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.LocationId).HasColumnName("Location_Id");
        });

        modelBuilder.Entity<BinColor>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_DB6D270ECF03485EB37775287403C031");
                    tb.HasTrigger("MSmerge_ins_DB6D270ECF03485EB37775287403C031");
                    tb.HasTrigger("MSmerge_upd_DB6D270ECF03485EB37775287403C031");
                });

            entity.HasIndex(e => e.BinName, "IX_BinColors_1").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BinColors_UID")
                .HasColumnName("UID");
            entity.Property(e => e.BinName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ColorId).HasColumnName("ColorID");
            entity.Property(e => e.LocationId)
                .HasDefaultValue(26)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BinColors_LocationID")
                .HasColumnName("LocationID");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_42B813C36C01448AAC04F74564289034");
                    tb.HasTrigger("MSmerge_ins_42B813C36C01448AAC04F74564289034");
                    tb.HasTrigger("MSmerge_upd_42B813C36C01448AAC04F74564289034");
                    tb.HasTrigger("UpdateCrop_Varieties");
                });

            entity.HasIndex(e => e.Id, "IX_Items").IsUnique();

            entity.HasIndex(e => e.Description, "IX_Items_1").IsUnique();

            entity.HasIndex(e => e.Dept, "IX_Items_Dept");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Items_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Dept)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Items_Dept");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Flc).HasColumnName("FLC");
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ItemType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NotInUse).HasAnnotation("Relational:DefaultConstraintName", "DF_Items_NotInUse");
            entity.Property(e => e.StoreLocation).HasColumnName("Store_Location");
            entity.Property(e => e.Uomcode)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("UOMCode");

            entity.HasOne(d => d.ItemTypeNavigation).WithMany(p => p.Items)
                .HasPrincipalKey(p => p.Description)
                .HasForeignKey(d => d.ItemType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Items_Item_Types");
        });

        modelBuilder.Entity<ItemLocation>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_ItemLocation");

            entity.ToTable("Item_Location", tb =>
                {
                    tb.HasTrigger("MSmerge_del_AC164A58E68D4720BB15CD7439DCF11D");
                    tb.HasTrigger("MSmerge_ins_AC164A58E68D4720BB15CD7439DCF11D");
                    tb.HasTrigger("MSmerge_upd_AC164A58E68D4720BB15CD7439DCF11D");
                    tb.HasTrigger("trigger_Insert_Lot_Analysys");
                });

            entity.HasIndex(e => new { e.Id, e.LocationId }, "IX_Item_Location_ID_Location").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_smItem_Location_UID")
                .HasColumnName("UID");
            entity.Property(e => e.DefaultValue).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Inactive).HasAnnotation("Relational:DefaultConstraintName", "DF_Item_Location_Inactive");
            entity.Property(e => e.LocationId).HasColumnName("Location_ID");
            entity.Property(e => e.Lot).HasMaxLength(100);
            entity.Property(e => e.NotInUse).HasAnnotation("Relational:DefaultConstraintName", "DF_Item_Location_NotInUse");
            entity.Property(e => e.Price).HasColumnType("money");

            entity.HasOne(d => d.Location).WithMany(p => p.ItemLocations)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Item_Location_Item_Location");
        });

        modelBuilder.Entity<ItemType>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Item_Types", tb =>
                {
                    tb.HasTrigger("MSmerge_del_AED7848748E645D2B2585108063E83F8");
                    tb.HasTrigger("MSmerge_ins_AED7848748E645D2B2585108063E83F8");
                    tb.HasTrigger("MSmerge_upd_AED7848748E645D2B2585108063E83F8");
                });

            entity.HasIndex(e => e.Description, "IX_Item_Types").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Item_Types_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_4E1E99E847324753AAB4F20B38B800DE");
                    tb.HasTrigger("MSmerge_ins_4E1E99E847324753AAB4F20B38B800DE");
                    tb.HasTrigger("MSmerge_upd_4E1E99E847324753AAB4F20B38B800DE");
                });

            entity.HasIndex(e => e.Id, "IX_Locations").IsUnique();

            entity.HasIndex(e => e.LocationCode, "IX_Locations_2").IsUnique();

            entity.HasIndex(e => e.Description, "IX_Locations_Description").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Locations_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Address1).HasMaxLength(255);
            entity.Property(e => e.Address2).HasMaxLength(255);
            entity.Property(e => e.Address3).HasMaxLength(255);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.LocationCode).HasColumnName("Location_Code");
            entity.Property(e => e.PlcPcAddress)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("PLC_PC_Address");
            entity.Property(e => e.ReportPrinter)
                .HasMaxLength(255)
                .HasColumnName("Report_Printer");
            entity.Property(e => e.TicketPrinter)
                .HasMaxLength(255)
                .HasColumnName("Ticket_Printer");
            entity.Property(e => e.TicketSeed)
                .HasDefaultValue(1000)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Locations_Ticket_Seed")
                .HasColumnName("Ticket_Seed");
            entity.Property(e => e.WebsiteAddress)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Website_Address");
        });

        modelBuilder.Entity<Lot>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_Lots_1");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_763C502766814850B184DB625C68F6A1");
                    tb.HasTrigger("MSmerge_ins_763C502766814850B184DB625C68F6A1");
                    tb.HasTrigger("MSmerge_upd_763C502766814850B184DB625C68F6A1");
                });

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CurrentLabUid).HasColumnName("Current_Lab_UID");
            entity.Property(e => e.DateCreated)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_DateCreated")
                .HasColumnType("datetime");
            entity.Property(e => e.Germination)
                .HasDefaultValue(0.8500m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Germination")
                .HasColumnType("decimal(10, 4)");
            entity.Property(e => e.Inactive).HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Inactive");
            entity.Property(e => e.InertMatter)
                .HasDefaultValue(0.0200m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Inert_Matter")
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("Inert_Matter");
            entity.Property(e => e.ItemLocationUid).HasColumnName("ItemLocationUID");
            entity.Property(e => e.Lot1)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Lot");
            entity.Property(e => e.Notes).HasColumnType("text");
            entity.Property(e => e.OtherCrop)
                .HasDefaultValue(0.0005m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Other_Crop")
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("Other_Crop");
            entity.Property(e => e.PureSeed)
                .HasDefaultValue(0.9800m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Pure_Seed")
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("Pure_Seed");
            entity.Property(e => e.WeedSeed)
                .HasDefaultValue(0.0003m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lots_Weed_Seed")
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("Weed_Seed");

            entity.HasOne(d => d.ItemLocationU).WithMany(p => p.Lots)
                .HasForeignKey(d => d.ItemLocationUid)
                .HasConstraintName("FK_Lots_Item_Location");
        });

        modelBuilder.Entity<LotAnalysis>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Lot_Analysis", tb =>
                {
                    tb.HasTrigger("MSmerge_del_DE8A66342C784D8080A308E5B88BF288");
                    tb.HasTrigger("MSmerge_ins_DE8A66342C784D8080A308E5B88BF288");
                    tb.HasTrigger("MSmerge_upd_DE8A66342C784D8080A308E5B88BF288");
                });

            entity.HasIndex(e => new { e.Lot, e.LocationId, e.Id }, "IX_Lot_Analysis").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lot_Analysis_UID")
                .HasColumnName("UID");
            entity.Property(e => e.DateTested)
                .HasColumnType("datetime")
                .HasColumnName("Date_Tested");
            entity.Property(e => e.Germination).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.InertMatter)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("Inert_Matter");
            entity.Property(e => e.LocationId).HasColumnName("Location_ID");
            entity.Property(e => e.Lot)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OtherCrop)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("Other_Crop");
            entity.Property(e => e.PureSeed)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("Pure_Seed");
            entity.Property(e => e.WeedSeed)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("Weed_Seed");
        });

        modelBuilder.Entity<PcAllowedToPrint>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("PC_Allowed_To_Print", tb =>
                {
                    tb.HasTrigger("MSmerge_del_D1E7B518787644F0A2B153A07628A542");
                    tb.HasTrigger("MSmerge_ins_D1E7B518787644F0A2B153A07628A542");
                    tb.HasTrigger("MSmerge_upd_D1E7B518787644F0A2B153A07628A542");
                });

            entity.HasIndex(e => e.PcAddress, "IX_PC_Allowed_To_Print").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PC_Allowed_To_Print_UID")
                .HasColumnName("UID");
            entity.Property(e => e.LocationId).HasColumnName("Location_ID");
            entity.Property(e => e.PcAddress)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("PC_Address");

            entity.HasOne(d => d.Location).WithMany(p => p.PcAllowedToPrints)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PC_Allowed_To_Print_PC_Allowed_To_Print");
        });

        modelBuilder.Entity<ScaleCamera>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Scale_Cameras", tb =>
                {
                    tb.HasTrigger("MSmerge_del_3E2942EADFD948B081DB0D51679FD796");
                    tb.HasTrigger("MSmerge_ins_3E2942EADFD948B081DB0D51679FD796");
                    tb.HasTrigger("MSmerge_upd_3E2942EADFD948B081DB0D51679FD796");
                });

            entity.HasIndex(e => new { e.LocationId, e.CameraLocation, e.ScaleDescription }, "IX_Scale_Cameras").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Scale_Cameras_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CameraLocation)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Camera_Location");
            entity.Property(e => e.LocationId).HasColumnName("Location_Id");
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.RtspAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("rtsp_Address");
            entity.Property(e => e.ScaleDescription)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("Scale_Description");
            entity.Property(e => e.UserName)
                .HasMaxLength(255)
                .HasColumnName("User_Name");
        });

        modelBuilder.Entity<SeedDepartment>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_SeedDepartments");

            entity.ToTable("Seed_Departments", tb =>
                {
                    tb.HasTrigger("MSmerge_del_4949DCE28B6A4D0193D5097F9DDFF4B1");
                    tb.HasTrigger("MSmerge_ins_4949DCE28B6A4D0193D5097F9DDFF4B1");
                    tb.HasTrigger("MSmerge_upd_4949DCE28B6A4D0193D5097F9DDFF4B1");
                });

            entity.HasIndex(e => e.Id, "IX_SeedDepartments").IsUnique();

            entity.HasIndex(e => e.Description, "IX_SeedDepartments_1").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SeedDepartments_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NotUsed)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Departments_Not_Used")
                .HasColumnName("Not_Used");
            entity.Property(e => e.SpringWheat)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Departments_Sprint_Wheat")
                .HasColumnName("Spring_Wheat");
        });

        modelBuilder.Entity<SeedTicket>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Seed_Tickets", tb =>
                {
                    tb.HasTrigger("MSmerge_del_CA42CFC60820454DA4020AFF3C484D56");
                    tb.HasTrigger("MSmerge_ins_CA42CFC60820454DA4020AFF3C484D56");
                    tb.HasTrigger("MSmerge_upd_CA42CFC60820454DA4020AFF3C484D56");
                });

            entity.HasIndex(e => e.LocationId, "IX_Seed_Tickets");

            entity.HasIndex(e => new { e.Ticket, e.LocationId }, "IX_Seed_Tickets_Ticket_Location")
                .IsUnique()
                .HasFilter("([Ticket] IS NOT NULL)");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Tickets_UID")
                .HasColumnName("UID");
            entity.Property(e => e.BagCnt).HasColumnName("Bag_Cnt");
            entity.Property(e => e.BagSize).HasColumnName("Bag_Size");
            entity.Property(e => e.Bol)
                .HasMaxLength(50)
                .HasColumnName("BOL");
            entity.Property(e => e.Complete).HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Tickets_Complete");
            entity.Property(e => e.GrowerId).HasColumnName("Grower_ID");
            entity.Property(e => e.GrowerName)
                .HasMaxLength(250)
                .HasColumnName("Grower_Name");
            entity.Property(e => e.LocationId).HasColumnName("Location_ID");
            entity.Property(e => e.Pending).HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Tickets_Pending");
            entity.Property(e => e.Po)
                .HasMaxLength(50)
                .HasColumnName("PO");
            entity.Property(e => e.ReadOnly).HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Tickets_ReadOnly");
            entity.Property(e => e.TicketDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Tickets_Ticket_Date")
                .HasColumnType("datetime")
                .HasColumnName("Ticket_Date");
            entity.Property(e => e.TicketType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Ticket_Type");
            entity.Property(e => e.TruckId)
                .HasMaxLength(50)
                .HasColumnName("Truck_ID");
            entity.Property(e => e.Weighmaster).HasMaxLength(255);
        });

        modelBuilder.Entity<SeedTicketMisc>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Seed_Ticket_Misc", tb =>
                {
                    tb.HasTrigger("MSmerge_del_02ACC278A6734828B2C3448B1B4243E0");
                    tb.HasTrigger("MSmerge_ins_02ACC278A6734828B2C3448B1B4243E0");
                    tb.HasTrigger("MSmerge_upd_02ACC278A6734828B2C3448B1B4243E0");
                });

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Ticket_Misc_UID")
                .HasColumnName("UID");
            entity.Property(e => e.Comment)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ItemId).HasColumnName("Item_Id");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.SeedTicketUid).HasColumnName("Seed_Ticket_UID");

            entity.HasOne(d => d.SeedTicketU).WithMany(p => p.SeedTicketMiscs)
                .HasForeignKey(d => d.SeedTicketUid)
                .HasConstraintName("FK_Seed_Ticket_Misc_Seed_Tickets");
        });

        modelBuilder.Entity<SeedTicketTreatment>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_Treatments");

            entity.ToTable("Seed_Ticket_Treatments", tb =>
                {
                    tb.HasTrigger("MSmerge_del_9D56F9965A824B0AAC575EE725C2431F");
                    tb.HasTrigger("MSmerge_ins_9D56F9965A824B0AAC575EE725C2431F");
                    tb.HasTrigger("MSmerge_upd_9D56F9965A824B0AAC575EE725C2431F");
                });

            entity.HasIndex(e => e.SeedTicketUid, "IX_Seed_Ticket_Treatments");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Treatments_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CustomName)
                .HasMaxLength(250)
                .HasColumnName("Custom_Name");
            entity.Property(e => e.PcAddress)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("PC_Address");
            entity.Property(e => e.SeedTicketUid).HasColumnName("Seed_Ticket_UID");
            entity.Property(e => e.SentToPlc).HasColumnName("Sent_To_PLC");
            entity.Property(e => e.TreatmentId).HasColumnName("Treatment_ID");

            entity.HasOne(d => d.SeedTicketU).WithMany(p => p.SeedTicketTreatments)
                .HasForeignKey(d => d.SeedTicketUid)
                .HasConstraintName("FK_Seed_Ticket_Treatments_Seed_Tickets");
        });

        modelBuilder.Entity<SeedTicketVariety>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK_Ticket_Varieties");

            entity.ToTable("Seed_Ticket_Varieties", tb =>
                {
                    tb.HasTrigger("MSmerge_del_717A07D4DD1C4EBC8ECF86DA0C94C1EE");
                    tb.HasTrigger("MSmerge_ins_717A07D4DD1C4EBC8ECF86DA0C94C1EE");
                    tb.HasTrigger("MSmerge_upd_717A07D4DD1C4EBC8ECF86DA0C94C1EE");
                });

            entity.HasIndex(e => e.SeedTicketUid, "IX_Seed_Ticket_Varieties");

            entity.HasIndex(e => e.VarietyId, "IX_Seed_Ticket_Varieties_1");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Ticket_Varieties_UID")
                .HasColumnName("UID");
            entity.Property(e => e.BinName)
                .HasMaxLength(20)
                .HasColumnName("Bin_Name");
            entity.Property(e => e.CustomName)
                .HasMaxLength(250)
                .HasColumnName("Custom_Name");
            entity.Property(e => e.LabNumber)
                .HasMaxLength(50)
                .HasColumnName("Lab_Number");
            entity.Property(e => e.Lot).HasMaxLength(50);
            entity.Property(e => e.PcAddress)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("PC_Address");
            entity.Property(e => e.PercentOfLoad).HasColumnName("Percent_Of_Load");
            entity.Property(e => e.SeedTicketUid).HasColumnName("Seed_Ticket_UID");
            entity.Property(e => e.SentToPlc).HasColumnName("Sent_To_PLC");
            entity.Property(e => e.VarietyId).HasColumnName("Variety_ID");

            entity.HasOne(d => d.SeedTicketU).WithMany(p => p.SeedTicketVarieties)
                .HasForeignKey(d => d.SeedTicketUid)
                .HasConstraintName("FK_Seed_Ticket_Varieties_Seed_Tickets");
        });

        modelBuilder.Entity<SeedTicketWeight>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Seed_Ticket_Weights", tb =>
                {
                    tb.HasTrigger("MSmerge_del_99F0BC79E9214F249D7D2BE994967C50");
                    tb.HasTrigger("MSmerge_ins_99F0BC79E9214F249D7D2BE994967C50");
                    tb.HasTrigger("MSmerge_upd_99F0BC79E9214F249D7D2BE994967C50");
                });

            entity.HasIndex(e => e.SeedTicketUid, "IX_Seed_Ticket_Weights");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Ticket_Weights_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Ticket_Weights_CreationDate")
                .HasColumnType("datetime")
                .HasColumnName("Creation_Date");
            entity.Property(e => e.EndingTime)
                .HasColumnType("datetime")
                .HasColumnName("Ending_Time");
            entity.Property(e => e.EndingWeight).HasColumnName("Ending_Weight");
            entity.Property(e => e.InboundScale)
                .HasMaxLength(50)
                .HasColumnName("Inbound_Scale");
            entity.Property(e => e.ManualIn).HasColumnName("Manual_In");
            entity.Property(e => e.ManualOut).HasColumnName("Manual_Out");
            entity.Property(e => e.OutboundScale)
                .HasMaxLength(50)
                .HasColumnName("Outbound_Scale");
            entity.Property(e => e.PcWeightInAddress)
                .HasMaxLength(30)
                .HasColumnName("PC_Weight_In_Address");
            entity.Property(e => e.PcWeightOutAddress)
                .HasMaxLength(30)
                .HasColumnName("PC_Weight_Out_Address");
            entity.Property(e => e.SeedTicketUid).HasColumnName("Seed_Ticket_UID");
            entity.Property(e => e.StartingTime)
                .HasColumnType("datetime")
                .HasColumnName("Starting_Time");
            entity.Property(e => e.StartingWeight).HasColumnName("Starting_Weight");

            entity.HasOne(d => d.SeedTicketU).WithMany(p => p.SeedTicketWeights)
                .HasForeignKey(d => d.SeedTicketUid)
                .HasConstraintName("FK_Seed_Ticket_Weights_Seed_Tickets");
        });

        modelBuilder.Entity<SeedTrait>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Seed_Trait", tb =>
                {
                    tb.HasTrigger("MSmerge_del_F2779022A4464D8D9B7244A9E549DBF7");
                    tb.HasTrigger("MSmerge_ins_F2779022A4464D8D9B7244A9E549DBF7");
                    tb.HasTrigger("MSmerge_upd_F2779022A4464D8D9B7244A9E549DBF7");
                });

            entity.HasIndex(e => new { e.ItemId, e.TraitId }, "IX_Seed_Trait").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Seed_Trait_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ItemId).HasColumnName("Item_Id");
            entity.Property(e => e.TraitId).HasColumnName("Trait_Id");

            entity.HasOne(d => d.Item).WithMany(p => p.SeedTraits)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_Seed_Trait_Items");

            entity.HasOne(d => d.Trait).WithMany(p => p.SeedTraits)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.TraitId)
                .HasConstraintName("FK_Seed_Trait_Trait");
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("System_Log", tb =>
                {
                    tb.HasTrigger("MSmerge_del_304E984623D54458B0A244A91A18D507");
                    tb.HasTrigger("MSmerge_ins_304E984623D54458B0A244A91A18D507");
                    tb.HasTrigger("MSmerge_upd_304E984623D54458B0A244A91A18D507");
                });

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_System_Log_UID")
                .HasColumnName("UID");
            entity.Property(e => e.CodeSource)
                .IsRequired()
                .HasColumnName("Code_Source");
            entity.Property(e => e.LocationId).HasColumnName("Location_Id");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Operator).HasMaxLength(255);
            entity.Property(e => e.PcAddress)
                .HasMaxLength(255)
                .HasColumnName("PC_Address");
            entity.Property(e => e.ServerName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("Server_Name");
            entity.Property(e => e.TimeDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_System_Log_Time_Date")
                .HasColumnType("datetime")
                .HasColumnName("Time_Date");
        });

        modelBuilder.Entity<Trait>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("Trait", tb =>
                {
                    tb.HasTrigger("MSmerge_del_51C97BCEA4554571B963C73D4863FD26");
                    tb.HasTrigger("MSmerge_ins_51C97BCEA4554571B963C73D4863FD26");
                    tb.HasTrigger("MSmerge_upd_51C97BCEA4554571B963C73D4863FD26");
                });

            entity.HasIndex(e => e.Description, "IX_Trait_Description").IsUnique();

            entity.HasIndex(e => e.Id, "IX_Trait_Id").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trait_UID")
                .HasColumnName("UID");
            entity.Property(e => e.ColorIndex).HasColumnName("Color_Index");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Duration)
                .HasDefaultValue(20)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Trait_Duration");
            entity.Property(e => e.Id).HasColumnName("ID");
        });

        modelBuilder.Entity<TreatmentWeight>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("MSmerge_del_9CC32660E1B84B84B70A845639B470A5");
                    tb.HasTrigger("MSmerge_ins_9CC32660E1B84B84B70A845639B470A5");
                    tb.HasTrigger("MSmerge_upd_9CC32660E1B84B84B70A845639B470A5");
                });

            entity.HasIndex(e => new { e.ItemId, e.LocationId }, "IX_TreatmentWeights").IsUnique();

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TreatmentWeights_UID")
                .HasColumnName("UID");
            entity.Property(e => e.LocationId).HasColumnName("Location_Id");

            entity.HasOne(d => d.Item).WithMany(p => p.TreatmentWeights)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_TreatmentWeights_Items");

            entity.HasOne(d => d.Location).WithMany(p => p.TreatmentWeights)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_TreatmentWeights_Locations");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}