// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Agvantage_Transfer.AtModels;

public partial class AtDbContext : DbContext
{
    public AtDbContext(DbContextOptions<AtDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AgvantageTransferLog> AgvantageTransferLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AgvantageTransferLog>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("AgvantageTransferLog");

            entity.Property(e => e.Uid)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("UID");
            entity.Property(e => e.Event)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.TaskTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}