SELECT DISTINCT CATAGORY
FROM
(
    -- Force-include Service
    SELECT 'SERVICE' FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'MISC' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'SHIPPING' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'FEE' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'WHEAT' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'PULSE' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'CORN' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'BARLEY' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
    SELECT 'GARBS' AS CATAGORY FROM SYSIBM.SYSDUMMY1    UNION
            

    -- Departments from U4DEPT
    SELECT
        CASE
            WHEN DPDEPT = 16 THEN 'PEA'
            WHEN DPDEPT = 18 THEN 'GRB'
            WHEN DPDEPT IN (21, 88, 89) THEN 'BLY'
            WHEN DPDEPT = 22 THEN 'OAT'
            WHEN DPDEPT = 90 THEN 'MISC'
            WHEN DPDEPT IN (85, 86) THEN 'WHC'
            WHEN DPDEPT IN (28, 29) THEN 'CHEM'
            WHEN DPDEPT IN (31, 32) THEN 'GRASS'
            WHEN DPDEPT IN (71, 72, 73, 77, 82, 83) THEN 'SWH'
            WHEN DPDEPT IN (74, 76, 84) THEN 'DNS'
            WHEN DPDEPT IN (75, 80, 81, 87) THEN 'HRW'
        END AS CATAGORY
    FROM COMDATA.U4DEPT
    WHERE DPDEPT NOT IN
    (
        1,10,12,13,14,15,17,19,20,27,33,50,
        60,61,62,63,64,65,66,69,70,91,92,
        93,95,97,99
    )

    UNION

    -- Departments from U5CROPS
    SELECT
        CASE
            WHEN CRCROP IN (90,85) THEN 'PEA'
            WHEN CRCROP IN (89,26) THEN 'OAT'
            WHEN CRCROP IN (30,31) THEN 'CORN'
            WHEN LOCATE(' ', CRLCDE) = 0 THEN CRLCDE
            ELSE SUBSTR(CRLCDE, 1, LOCATE(' ', CRLCDE) - 1)
        END AS CATAGORY
    FROM COMDATA.U5CROPS
) ALLDEPTS
ORDER BY CATAGORY;
