 
    SELECT
    CRCROP  AS IMPROD,


    TRIM(
        CASE
            WHEN CRCROP NOT IN (38,42,46) AND   UPPER(CRLCDE) LIKE 'PEA %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'BLY %' THEN SUBSTR(CRLCDE, 5)
            WHEN CRCROP NOT IN (2,82) AND  UPPER(CRLCDE) LIKE 'SWH %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'CRN %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'LEN %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'GRB %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'SRW %' THEN SUBSTR(CRLCDE, 5)
            WHEN CRCROP NOT IN ( 11,10) AND  UPPER(CRLCDE) LIKE 'HRW %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'SUN %' THEN SUBSTR(CRLCDE, 5)           
            WHEN UPPER(CRLCDE) LIKE 'CAN %' THEN SUBSTR(CRLCDE, 5)                        
            WHEN CRCROP NOT IN  (11) AND UPPER(CRLCDE) LIKE 'HWW %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'SAF %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'SOY %' THEN SUBSTR(CRLCDE, 5)
            WHEN UPPER(CRLCDE) LIKE 'MUS %' THEN SUBSTR(CRLCDE, 5)
            WHEN CRCROP NOT IN  (16,14,84) AND UPPER(CRLCDE) LIKE 'DNS %' THEN SUBSTR(CRLCDE, 5)

            ELSE CRLCDE
        END
        
    ) AS IMDESC,
    
     CASE WHEN CRCROP IN( 82,84,86,87,88,85,89,90 ,80,70  ) THEN 'SEED' ELSE 'WAREHOUSE' END AS SYSTEM_USAGE, 
    

     CAST(NULL AS NVARCHAR(10)) AS HERBICIDE_SYSTEM, 

     CASE 
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% FALL %' THEN 'FALL' 
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% FALL%' THEN 'FALL'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%FALL %' THEN 'FALL'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% WINTER %' THEN 'WINTER' 
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% WINTER%' THEN 'WINTER'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%WINTER %' THEN 'WINTER'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% SPRING %' THEN 'SPRING'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '% SPRING%' THEN 'SPRING'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%SPRING %' THEN 'SPRING'
        
        END 
    AS SEASON,
    
     CAST(NULL AS NVARCHAR(10)) AS LAND_PROGRAM, 
     
     CASE 
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%COMMON%' THEN 'COMMON' 
        
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%REGISTARD%' THEN 'REGISTERED'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%REGISTERED%' THEN 'REGISTERED'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%CERTIFIED%' THEN 'CERTIFIED'
        WHEN  UPPER(TRIM(CRCROP)) LIKE '%FOUNDATION%' THEN 'FOUNDATION'
        
        END 
    AS CERT_CLASS,
    

     CASE
        WHEN UPPER(TRIM(CRCROP)) LIKE '%CLEAN %' THEN 'CLEAN'
        WHEN UPPER(TRIM(CRCROP)) LIKE '% CLEAN%' THEN 'CLEAN'
        WHEN UPPER(TRIM(CRCROP)) LIKE '%INDIRT%' THEN 'IN-DIRT'
        WHEN UPPER(TRIM(CRCROP)) LIKE '%IN DIRT%' THEN 'IN-DIRT'
        WHEN UPPER(TRIM(CRCROP)) LIKE '%IN_DIRT%' THEN 'IN-DIRT'
     END AS CONDITION,
     
 


 CASE WHEN CRCROP IN( 82,84,86,87,88,85,89,90 ,80,70  ) THEN 0 ELSE 1 END AS ISACTIVE,    
 
 CRCROP AS CROPID,



  
 (
    CASE
        WHEN CRCROP IN (90,38)  THEN 'GPEA'
        WHEN CRCROP IN (39,46)  THEN 'PEA'
        WHEN CRCROP IN (85,42)  THEN 'YPEA'
        WHEN CRCROP IN (7)      THEN 'MUS'
        WHEN CRCROP IN (54)     THEN 'GARBS'
        WHEN CRCROP IN (34)     THEN 'MIXGRN'
        WHEN CRCROP IN (50)     THEN 'LENT'
        WHEN CRCROP IN (10,11,12) THEN 'HRW'
        WHEN CRCROP IN (89,26)  THEN 'OAT'
        WHEN CRCROP IN (30,31)  THEN 'CORN'
        WHEN LOCATE(' ', CRLCDE) = 0 THEN TRIM(CRLCDE)
        ELSE SUBSTR(CRLCDE, 1, LOCATE(' ', CRLCDE) - 1)
    END
    ||
    CASE
        WHEN CRCROP IN (82,84,86,87,88,85,89,90,80,70) THEN ' (SEED)'
        ELSE ''
    END
) AS PRODUCTCODE,

  
    CASE
        WHEN CRCROP IN (38,39,42,46,50,54,55,90,85) THEN 'PULSES'
        WHEN CRCROP IN (34) THEN 'SPECIAL'
        WHEN CRCROP IN (7,18,66,74,76,70) THEN 'OILSEED'
        WHEN CRCROP IN (88,22,30,31,89,76,26,5,10,11,12,14,15,2,3,58,59,6,62,80,82,84,86,87) THEN 'WHEAT'
        WHEN CRCROP IN (34) THEN 'SPECIAL'
    END AS CATEGORY,

   CASE
        WHEN UPPER(TRIM(CRCRDE)) LIKE '%PEA%' THEN 'PEA'
        WHEN CRCROP IN (89,76,26) THEN 'OATS'
        WHEN CRCROP IN (34) THEN 'SPECIAL'
        WHEN CRCROP IN (30,31) THEN 'CORN'
        WHEN CRCROP IN (88,22) THEN 'BARLEY'
        WHEN CRCROP IN (7,18,66,74,76,70) THEN 'OILSEED'
        WHEN CRCROP IN (5,10,11,12,14,15,2,3,58,59,6,62,80,82,84,86,87) THEN 'WHEAT'
        WHEN CRCROP IN (34) THEN 'SPECIAL'
    END AS PRODUCTGROUP
     

FROM COMDATA.U5CROPS



