-- select * from COMDATA.U4ITMMR


select "IMPROD","IMDESC","IMFLCD","IMDEPT","IMDEL" from COMDATA.U4ITMMR

SELECT
    DPDEPT,
    DPDESC,
    CASE
        WHEN LOCATE(' ', TRIM(DPDESC)) = 0
            THEN TRIM(DPDESC)
        ELSE SUBSTR(TRIM(DPDESC), 1, LOCATE(' ', TRIM(DPDESC)) - 1)
    END AS FirstWord
FROM COMDATA.U4DEPT
ORDER BY DPDEPT
