// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class AccountCustomPricing
{
    public Guid Uid { get; set; }

    public Guid AccountUid { get; set; }

    public string Description { get; set; }

    public int SiteId { get; set; }

    public Guid ProductVarietyItemUid { get; set; }

    public decimal Price { get; set; }

    public bool Active { get; set; }

    public string Notes { get; set; }

    public bool CustomerPaysRoyalities { get; set; }

    public decimal DiscountPercent { get; set; }

    public virtual ProductVarietyItem ProductVarietyItemU { get; set; }

    public virtual Site Site { get; set; }
}