// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class Log
{
    public Guid Uid { get; set; }

    public DateTime TimeDate { get; set; }

    public string LogType { get; set; }

    public string Message { get; set; }

    public string Dbserver { get; set; }
}