// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class Lot
{
    public long Id { get; set; }

    public int SiteId { get; set; }

    public DateTime CreationDate { get; set; }

    public long ProductVarietyItemId { get; set; }

    public bool Closed { get; set; }

    public string Notes { get; set; }

    public string Description { get; set; }

    public virtual ICollection<LotLab> LotLabs { get; set; } = new List<LotLab>();

    public virtual ProductVarietyItem ProductVarietyItem { get; set; }

    public virtual ICollection<PurchaseOrderLineItem> PurchaseOrderLineItems { get; set; } = new List<PurchaseOrderLineItem>();

    public virtual Site Site { get; set; }
}