// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class SiteDistrict
{
    public int Id { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Site> Sites { get; set; } = new List<Site>();
}