// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class SplitGroupPercent
{
    public int Id { get; set; }

    public int SplitGroupId { get; set; }

    public long AccountId { get; set; }

    public decimal SplitPercent { get; set; }

    public virtual Account Account { get; set; }

    public virtual SplitGroup SplitGroup { get; set; }
}