// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class User
{
    public long Id { get; set; }

    public int UserPin { get; set; }

    public string Name { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<UserPrivilege> UserPrivileges { get; set; } = new List<UserPrivilege>();
}