// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgvantageAPI.Models;

public partial class WeightSheet
{
    public Guid Uid { get; set; }

    public long Id { get; set; }

    public int SiteId { get; set; }

    public int WeightSheetType { get; set; }

    public DateTime CreationDate { get; set; }

    public int StatusId { get; set; }

    public string InternalNotes { get; set; }

    public string Notes { get; set; }

    public virtual Site Site { get; set; }

    public virtual WeightSheetStatus Status { get; set; }
}