// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace RWSP.Models
{

    public partial class LocationOption
    {
        public Guid Uid { get; set; }

        public int LocationId { get; set; }

        public string Description { get; set; }

        public string Value { get; set; }

        public Guid Rowguid { get; set; }

    
    }
}