// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class Glaccount
{
    public int Id { get; set; }

    public int LocationCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string AccountNumber { get; set; }

    public string AccountType { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Breeder> Breeders { get; set; } = new List<Breeder>();

    public virtual GlchemicalAccount GlchemicalAccount { get; set; }

    public virtual GlgrainAccount GlgrainAccount { get; set; }

    public virtual GlmiscAccount GlmiscAccount { get; set; }

    public virtual ICollection<GlserviceAccount> GlserviceAccounts { get; set; } = new List<GlserviceAccount>();

    public virtual GltreatmentAccount GltreatmentAccount { get; set; }

    public virtual ICollection<ProductClass> ProductClasses { get; set; } = new List<ProductClass>();

    public virtual ICollection<ProductCondition> ProductConditions { get; set; } = new List<ProductCondition>();

    public virtual ICollection<ProductMeasurementUnit> ProductMeasurementUnits { get; set; } = new List<ProductMeasurementUnit>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}