// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ProductMeasurementUnit
{
    public int Id { get; set; }

    public int UomId { get; set; }

    public int GlAccountId { get; set; }

    public bool DefaultUom { get; set; }

    public virtual Glaccount GlAccount { get; set; }

    public virtual UnitOfMeasure Uom { get; set; }
}