// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrainManagement.Models;

public partial class ProductType
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int ProductId { get; set; }

    public bool Active { get; set; }

    public DateTime MarketPriceDate { get; set; }

    public decimal MarketPrice { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductVariety> ProductVarieties { get; set; } = new List<ProductVariety>();
}